#!/usr/bin/env python3
import json
from pathlib import Path
OUT = Path(__file__).parent / 'data'

recipes = [

# ── SNACKS ────────────────────────────────────────────────────────────────────

{"name": "Bacon Wrapped Dates",
 "meal_type": "Snacks", "servings": 8, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 180, "protein_g": 6, "carbs_g": 22, "fat_g": 8},
 "ingredients": [
   {"amount": "24",        "item": "Medjool dates, pitted",        "store_section": "Produce"},
   {"amount": "12 strips", "item": "bacon, halved crosswise",      "store_section": "Meat/Seafood"},
   {"amount": "4 oz",      "item": "goat cheese or blue cheese",   "store_section": "Dairy/Eggs"},
   {"amount": "24",        "item": "toothpicks",                   "store_section": "Other"},
 ],
 "instructions": [
   "Preheat oven to 400°F. Line a baking sheet with a wire rack.",
   "Stuff each date with a small amount of goat cheese.",
   "Wrap each date with a half strip of bacon and secure with a toothpick.",
   "Place on the rack and bake 18-20 minutes until bacon is crispy.",
   "Let cool slightly before serving — the filling is very hot.",
 ],
 "substitutions": {
   "dairy_free": "Skip the cheese filling.",
   "gluten_free": "Already gluten-free.",
 },
 "notes": "The sweet-salty-savory combination makes these dangerously addictive."},

{"name": "Buffalo Chicken Dip",
 "meal_type": "Snacks", "servings": 8, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 18, "carbs_g": 8, "fat_g": 20},
 "ingredients": [
   {"amount": "2 cups",    "item": "cooked chicken, shredded",     "store_section": "Meat/Seafood"},
   {"amount": "8 oz",      "item": "cream cheese, softened",       "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "Frank's RedHot or buffalo sauce","store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "ranch dressing",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "shredded cheddar cheese",      "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "shredded mozzarella",          "store_section": "Dairy/Eggs"},
   {"amount": "tortilla chips or celery", "item": "for serving",   "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 375°F.",
   "Beat cream cheese until smooth. Mix in buffalo sauce and ranch dressing.",
   "Fold in shredded chicken and half the cheddar.",
   "Spread into a baking dish. Top with remaining cheddar and mozzarella.",
   "Bake 20-25 minutes until bubbly and golden on top.",
   "Serve hot with tortilla chips and celery sticks.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cream cheese and vegan cheese.",
   "gluten_free": "Serve with gluten-free chips or veggies.",
   "low_carb": "Serve with celery and cucumber instead of chips.",
 }},

{"name": "Deviled Eggs",
 "meal_type": "Snacks", "servings": 12, "prep_time": "15 minutes", "cook_time": "12 minutes",
 "macros_per_serving": {"calories": 120, "protein_g": 8, "carbs_g": 2, "fat_g": 9},
 "ingredients": [
   {"amount": "12 large",  "item": "eggs",                         "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",   "item": "mayonnaise",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "Dijon mustard",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "apple cider vinegar",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",   "item": "paprika plus more for garnish","store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
   {"amount": "optional",  "item": "bacon crumbles and chives",    "store_section": "Meat/Seafood"},
 ],
 "instructions": [
   "Place eggs in a pot and cover with cold water by 1 inch.",
   "Bring to a boil, then cover and remove from heat. Let sit 10-12 minutes.",
   "Transfer to an ice bath for 10 minutes. Peel carefully.",
   "Halve eggs lengthwise. Pop yolks into a bowl.",
   "Mash yolks with mayo, mustard, vinegar, paprika, salt, and pepper until smooth.",
   "Pipe or spoon filling back into egg white halves.",
   "Garnish with paprika and optional bacon or chives.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Already gluten-free.",
 },
 "notes": "Older eggs peel more easily than fresh eggs for hard boiling."},

{"name": "Loaded Queso Dip",
 "meal_type": "Snacks", "servings": 8, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 240, "protein_g": 12, "carbs_g": 14, "fat_g": 16},
 "ingredients": [
   {"amount": "1 lb",      "item": "Velveeta or American cheese, cubed","store_section": "Dairy/Eggs"},
   {"amount": "1/2 lb",    "item": "ground beef or chorizo",           "store_section": "Meat/Seafood"},
   {"amount": "1 can",     "item": "Rotel diced tomatoes with chiles (10 oz)","store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",   "item": "milk",                             "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "cumin",                            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "chili powder",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "tortilla chips", "item": "for serving",                 "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Brown ground beef in a skillet. Drain fat. Season with cumin and chili powder.",
   "In a saucepan over low heat, melt Velveeta with milk, stirring frequently.",
   "Stir in Rotel tomatoes (with juice) and cooked meat.",
   "Stir until fully combined and smooth.",
   "Transfer to a slow cooker on warm setting to keep hot while serving.",
   "Serve with tortilla chips.",
 ],
 "substitutions": {
   "gluten_free": "Serve with gluten-free chips.",
   "vegetarian": "Skip the meat and add black beans instead.",
 }},

{"name": "Mini Corn Dogs",
 "meal_type": "Snacks", "servings": 6, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 220, "protein_g": 8, "carbs_g": 28, "fat_g": 9},
 "ingredients": [
   {"amount": "1 pkg",     "item": "cocktail sausages (14 oz)",    "store_section": "Meat/Seafood"},
   {"amount": "1 cup",     "item": "yellow cornmeal",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "all-purpose flour",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "sugar",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "baking powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",   "item": "salt",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "buttermilk",                   "store_section": "Dairy/Eggs"},
   {"amount": "2 large",   "item": "eggs",                         "store_section": "Dairy/Eggs"},
   {"amount": "oil",       "item": "for frying",                   "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Pat sausages dry and insert a small skewer or toothpick into each.",
   "Mix cornmeal, flour, sugar, baking powder, and salt.",
   "Whisk in buttermilk and eggs until smooth batter forms.",
   "Heat 2 inches of oil to 375°F.",
   "Dip each sausage in batter, letting excess drip off.",
   "Fry in batches 2-3 minutes until golden and cooked through.",
   "Drain on paper towels. Serve with ketchup and mustard.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk mixed with 1 tsp vinegar instead of buttermilk.",
   "gluten_free": "Use a gluten-free flour blend and certified GF cornmeal.",
 }},

{"name": "Pigs in a Blanket",
 "meal_type": "Snacks", "servings": 8, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 10, "carbs_g": 24, "fat_g": 16},
 "ingredients": [
   {"amount": "1 pkg",     "item": "cocktail sausages (14 oz)",    "store_section": "Meat/Seafood"},
   {"amount": "1 can",     "item": "refrigerated crescent roll dough","store_section": "Dairy/Eggs"},
   {"amount": "1 large",   "item": "egg, beaten (egg wash)",       "store_section": "Dairy/Eggs"},
   {"amount": "1 tbsp",    "item": "everything bagel seasoning",   "store_section": "Pantry/Dry Goods"},
   {"amount": "mustard",   "item": "for serving",                  "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 375°F. Line a baking sheet with parchment.",
   "Unroll crescent dough and separate into triangles. Cut each triangle into 3 smaller triangles.",
   "Place a sausage at the wide end of each triangle and roll toward the point.",
   "Arrange on baking sheet. Brush with egg wash and sprinkle with bagel seasoning.",
   "Bake 12-15 minutes until deep golden brown.",
   "Serve immediately with mustard.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free crescent dough if available.",
   "gluten_free": "Use a gluten-free pastry dough.",
 }},

# ── DESSERTS ─────────────────────────────────────────────────────────────────

{"name": "Better Than Sex Cake",
 "meal_type": "Desserts", "servings": 12, "prep_time": "15 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 6, "carbs_g": 62, "fat_g": 22},
 "ingredients": [
   {"amount": "1 box",     "item": "chocolate cake mix (plus ingredients on box)","store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",     "item": "sweetened condensed milk (14 oz)","store_section": "Pantry/Dry Goods"},
   {"amount": "1 jar",     "item": "caramel sauce (12 oz)",          "store_section": "Pantry/Dry Goods"},
   {"amount": "8 oz",      "item": "whipped topping (Cool Whip), thawed","store_section": "Frozen"},
   {"amount": "4",         "item": "Heath or Skor toffee bars, crushed","store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "chocolate chips",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Bake chocolate cake in a 9x13 pan according to package directions. Let cool 10 minutes.",
   "Use the handle of a wooden spoon to poke holes all over the warm cake.",
   "Pour sweetened condensed milk over the cake, letting it soak into the holes.",
   "Drizzle caramel sauce over the entire surface.",
   "Let cake cool completely to room temperature, then refrigerate 1 hour.",
   "Spread whipped topping evenly over the cold cake.",
   "Sprinkle crushed toffee bars and chocolate chips over the top.",
   "Refrigerate at least 2 hours or overnight before serving.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cake mix, coconut condensed milk, and dairy-free whipped topping.",
   "gluten_free": "Use a gluten-free chocolate cake mix.",
 },
 "notes": "Better the next day — make it the night before for the best flavor and texture."},

{"name": "Carrot Cake",
 "meal_type": "Desserts", "servings": 12, "prep_time": "20 minutes", "cook_time": "35 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 5, "carbs_g": 58, "fat_g": 20},
 "ingredients": [
   {"amount": "2 cups",    "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",    "item": "granulated sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",     "item": "baking soda",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",     "item": "cinnamon",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "salt",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "4 large",   "item": "eggs",                          "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",     "item": "vegetable oil",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "3 cups",    "item": "carrots, freshly grated",       "store_section": "Produce"},
   {"amount": "8 oz",      "item": "cream cheese, softened",        "store_section": "Dairy/Eggs"},
   {"amount": "4 tbsp",    "item": "butter, softened",              "store_section": "Dairy/Eggs"},
   {"amount": "2 cups",    "item": "powdered sugar",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease two 9-inch round cake pans.",
   "Whisk flour, sugar, baking soda, cinnamon, and salt.",
   "In another bowl, beat eggs, oil, and vanilla. Fold in grated carrots.",
   "Combine wet and dry ingredients until just mixed.",
   "Divide between pans and bake 30-35 minutes until a toothpick comes out clean.",
   "Cool completely.",
   "Beat cream cheese and butter until fluffy. Add powdered sugar and vanilla. Beat until smooth.",
   "Frost cake with cream cheese frosting.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cream cheese and butter for the frosting.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use flax eggs and dairy-free cream cheese.",
 }},

{"name": "Churros",
 "meal_type": "Desserts", "servings": 6, "prep_time": "15 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 4, "carbs_g": 38, "fat_g": 12},
 "ingredients": [
   {"amount": "1 cup",     "item": "water",                         "store_section": "Other"},
   {"amount": "1/2 cup",   "item": "butter",                        "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",     "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "3 large",   "item": "eggs",                          "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
   {"amount": "pinch",     "item": "salt",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "granulated sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "cinnamon",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "oil",       "item": "for frying",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "optional",  "item": "chocolate dipping sauce",       "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Bring water, butter, and salt to a boil in a saucepan.",
   "Add flour all at once and stir vigorously until dough pulls away from sides.",
   "Cool 5 minutes. Beat in eggs one at a time until smooth. Mix in vanilla.",
   "Transfer dough to a piping bag with a large star tip.",
   "Heat 2 inches of oil to 375°F.",
   "Pipe 6-inch lengths into the hot oil, cutting with scissors. Fry 3-4 minutes until golden.",
   "Mix sugar and cinnamon. Roll hot churros in cinnamon sugar immediately.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
 },
 "notes": "Eat immediately — churros lose their crunch quickly."},

{"name": "Funnel Cake",
 "meal_type": "Desserts", "servings": 4, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 6, "carbs_g": 52, "fat_g": 16},
 "ingredients": [
   {"amount": "2 cups",    "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "granulated sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "baking powder",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",   "item": "salt",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",   "item": "eggs",                          "store_section": "Dairy/Eggs"},
   {"amount": "1.5 cups",  "item": "milk",                          "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
   {"amount": "oil",       "item": "for frying",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "powdered sugar for dusting",    "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Whisk flour, sugar, baking powder, and salt.",
   "In another bowl, beat eggs, milk, and vanilla.",
   "Combine wet and dry until smooth batter forms.",
   "Heat 2 inches of oil to 375°F in a wide skillet.",
   "Pour batter through a funnel or squeeze bottle in circular and criss-cross patterns.",
   "Fry 2 minutes per side until golden brown. Drain on paper towels.",
   "Dust generously with powdered sugar. Serve immediately.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use plant milk and flax eggs.",
 }},

{"name": "Puppy Chow",
 "meal_type": "Desserts", "servings": 12, "prep_time": "10 minutes", "cook_time": "5 minutes",
 "macros_per_serving": {"calories": 220, "protein_g": 4, "carbs_g": 32, "fat_g": 10},
 "ingredients": [
   {"amount": "9 cups",    "item": "Rice Chex cereal",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "chocolate chips",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "peanut butter",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "4 tbsp",    "item": "butter",                        "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 cups",  "item": "powdered sugar",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Pour cereal into a very large bowl.",
   "Melt chocolate chips, peanut butter, and butter together in the microwave in 30-second intervals, stirring between each.",
   "Stir in vanilla until smooth.",
   "Pour chocolate mixture over cereal and gently fold until evenly coated.",
   "Transfer to a large zip-top bag. Add powdered sugar.",
   "Seal and shake until every piece is coated.",
   "Spread on a parchment-lined baking sheet to cool and set.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free chocolate chips and dairy-free butter.",
   "gluten_free": "Rice Chex is gluten-free — just verify your chocolate chips are too.",
   "nut_free": "Replace peanut butter with sunflower seed butter.",
 },
 "notes": "Also called Muddy Buddies. Keeps in an airtight container up to 1 week."},

{"name": "Red Velvet Cake",
 "meal_type": "Desserts", "servings": 12, "prep_time": "25 minutes", "cook_time": "35 minutes",
 "macros_per_serving": {"calories": 440, "protein_g": 5, "carbs_g": 62, "fat_g": 20},
 "ingredients": [
   {"amount": "2.5 cups",  "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 cups",  "item": "granulated sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "unsweetened cocoa powder",      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "baking soda",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "salt",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",   "item": "eggs",                          "store_section": "Dairy/Eggs"},
   {"amount": "1.5 cups",  "item": "vegetable oil",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "buttermilk",                    "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "red food coloring",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "white vinegar",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
   {"amount": "8 oz",      "item": "cream cheese, softened",        "store_section": "Dairy/Eggs"},
   {"amount": "4 tbsp",    "item": "butter, softened",              "store_section": "Dairy/Eggs"},
   {"amount": "2 cups",    "item": "powdered sugar",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease and flour two 9-inch round cake pans.",
   "Whisk flour, sugar, cocoa powder, baking soda, and salt.",
   "Beat oil, eggs, buttermilk, food coloring, vinegar, and vanilla together.",
   "Combine wet and dry until smooth.",
   "Divide between pans. Bake 30-35 minutes until toothpick comes out clean.",
   "Cool completely.",
   "Beat cream cheese and butter until fluffy. Add powdered sugar and beat until smooth.",
   "Frost between layers and over the outside of the cake.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free buttermilk (plant milk + 1 tbsp vinegar) and dairy-free cream cheese.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
 }},

{"name": "Tres Leches Cake",
 "meal_type": "Desserts", "servings": 12, "prep_time": "20 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 8, "carbs_g": 52, "fat_g": 16},
 "ingredients": [
   {"amount": "1 cup",     "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 tsp",   "item": "baking powder",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",   "item": "salt",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "5 large",   "item": "eggs, separated",               "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",     "item": "granulated sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1/3 cup",   "item": "whole milk",                    "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "vanilla extract",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",     "item": "sweetened condensed milk (14 oz)","store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",     "item": "evaporated milk (12 oz)",       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "heavy cream",                   "store_section": "Dairy/Eggs"},
   {"amount": "2 cups",    "item": "heavy cream for topping",       "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "powdered sugar",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease a 9x13 pan.",
   "Beat egg yolks and sugar until pale and thick. Mix in milk and vanilla.",
   "Fold in flour, baking powder, and salt.",
   "Beat egg whites to stiff peaks. Gently fold into batter in thirds.",
   "Bake 25-30 minutes until a toothpick comes out clean. Cool completely.",
   "Mix condensed milk, evaporated milk, and 1 cup heavy cream. Poke holes in cake.",
   "Pour three-milk mixture slowly over cake. Refrigerate 4 hours or overnight.",
   "Whip remaining cream with powdered sugar to stiff peaks. Spread over cake before serving.",
 ],
 "substitutions": {
   "dairy_free": "Use coconut condensed milk, coconut evaporated milk, and coconut cream.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
 },
 "notes": "The longer it soaks, the better. Overnight is ideal."},

]

for r in recipes:
    fn = r['name'].lower().replace(' ', '-').replace('&', 'and').replace("'", '').replace(',', '') + '.json'
    (OUT / fn).write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {fn}')
print(f'Done — {len(recipes)} snacks and desserts.')
