#!/usr/bin/env python3
import json
from pathlib import Path
OUT = Path(__file__).parent / 'data'

recipes = [

{"name": "Fish and Chips",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 580, "protein_g": 32, "carbs_g": 62, "fat_g": 22},
 "ingredients": [
   {"amount": "2 lbs",     "item": "cod or haddock fillets",       "store_section": "Meat/Seafood"},
   {"amount": "4 large",   "item": "russet potatoes, cut into fries","store_section": "Produce"},
   {"amount": "1.5 cups",  "item": "all-purpose flour",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "baking powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "cold beer or sparkling water", "store_section": "Beverages"},
   {"amount": "oil",       "item": "for deep frying",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "garlic powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "malt vinegar or tartar sauce", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Soak potato fries in cold water 30 minutes. Drain and dry thoroughly.",
   "Heat oil to 325°F. Fry potatoes 5-6 minutes until cooked but not browned. Drain.",
   "Increase oil to 375°F. Fry potatoes again 2-3 minutes until golden and crispy. Season with salt.",
   "Whisk flour, baking powder, garlic powder, salt, and pepper. Whisk in cold beer until smooth.",
   "Pat fish dry. Dip in batter and let excess drip off.",
   "Fry fish 4-5 minutes until deep golden brown. Drain on paper towels.",
   "Serve immediately with fries, malt vinegar or tartar sauce.",
 ],
 "substitutions": {
   "gluten_free": "Use rice flour and gluten-free sparkling water for the batter.",
   "dairy_free": "Already dairy-free.",
 },
 "notes": "Double-frying the chips is what makes them crispy. Do not skip the first fry."},

{"name": "Garlic Butter Steak",
 "meal_type": "Dinner", "servings": 2, "prep_time": "5 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 520, "protein_g": 48, "carbs_g": 4, "fat_g": 34},
 "ingredients": [
   {"amount": "2",         "item": "ribeye or New York strip steaks (1-inch thick)","store_section": "Meat/Seafood"},
   {"amount": "4 tbsp",    "item": "butter",                       "store_section": "Dairy/Eggs"},
   {"amount": "4 cloves",  "item": "garlic, smashed",              "store_section": "Produce"},
   {"amount": "4 sprigs",  "item": "fresh thyme or rosemary",      "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "vegetable oil",                "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "coarse salt and black pepper", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Take steaks out of fridge 30 minutes before cooking. Pat dry.",
   "Season very generously with salt and pepper on both sides.",
   "Heat oil in a cast iron skillet over high heat until smoking.",
   "Sear steaks 3-4 minutes without moving. Flip and cook 3 more minutes.",
   "Reduce heat to medium. Add butter, garlic, and herbs to pan.",
   "Tilt pan and spoon melted butter over steaks continuously for 2 minutes.",
   "Rest steaks 5 minutes before slicing.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter or skip basting.",
   "gluten_free": "Already gluten-free.",
   "low_carb": "Already low-carb — serve with roasted vegetables.",
 },
 "notes": "Do not skip the resting step. Slicing too early loses all the juices."},

{"name": "Garlic Parmesan Wings",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 42, "carbs_g": 8, "fat_g": 32},
 "ingredients": [
   {"amount": "3 lbs",     "item": "chicken wings",                "store_section": "Meat/Seafood"},
   {"amount": "6 tbsp",    "item": "butter, melted",               "store_section": "Dairy/Eggs"},
   {"amount": "6 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1 cup",     "item": "grated parmesan",              "store_section": "Dairy/Eggs"},
   {"amount": "1 tbsp",    "item": "baking powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "garlic powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "fresh parsley, chopped",       "store_section": "Produce"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Pat wings very dry. Toss with baking powder, garlic powder, salt, and pepper.",
   "Place on a wire rack over a baking sheet. Refrigerate uncovered 1 hour or overnight.",
   "Preheat oven to 425°F. Bake wings 40-45 minutes, flipping halfway, until crispy.",
   "Meanwhile, cook garlic in butter over medium heat 2 minutes until fragrant.",
   "Toss hot wings in garlic butter. Add parmesan and toss again to coat.",
   "Garnish with fresh parsley and serve immediately.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and skip parmesan.",
   "gluten_free": "Already gluten-free.",
   "low_carb": "Already low-carb.",
 },
 "notes": "Baking powder and drying the wings overnight is the secret to oven-crispy skin."},

{"name": "Lamb Chops with Herb Butter",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 520, "protein_g": 42, "carbs_g": 2, "fat_g": 36},
 "ingredients": [
   {"amount": "8",         "item": "lamb loin chops (1-inch thick)","store_section": "Meat/Seafood"},
   {"amount": "4 tbsp",    "item": "butter, softened",             "store_section": "Dairy/Eggs"},
   {"amount": "2 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1 tbsp",    "item": "fresh rosemary, minced",       "store_section": "Produce"},
   {"amount": "1 tbsp",    "item": "fresh thyme, minced",          "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "coarse salt and black pepper", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Mix softened butter with garlic, rosemary, and thyme. Roll in plastic wrap and refrigerate.",
   "Bring lamb chops to room temperature 20 minutes before cooking.",
   "Season generously with salt and pepper.",
   "Heat olive oil in a cast iron skillet over high heat.",
   "Sear chops 3-4 minutes per side for medium-rare. Do not crowd the pan.",
   "Rest 5 minutes. Top each chop with a slice of herb butter before serving.",
 ],
 "substitutions": {
   "dairy_free": "Skip herb butter or use dairy-free butter.",
   "gluten_free": "Already gluten-free.",
   "low_carb": "Already low-carb — serve with roasted asparagus.",
 },
 "notes": "Lamb is best at medium-rare (135°F internal). Do not overcook or it becomes tough."},

{"name": "Orange Chicken",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 32, "carbs_g": 52, "fat_g": 16},
 "ingredients": [
   {"amount": "2 lbs",     "item": "chicken thighs, boneless, cubed","store_section": "Meat/Seafood"},
   {"amount": "1/2 cup",   "item": "cornstarch",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",   "item": "eggs, beaten",                  "store_section": "Dairy/Eggs"},
   {"amount": "oil",       "item": "for frying",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",   "item": "orange juice",                  "store_section": "Beverages"},
   {"amount": "1/4 cup",   "item": "soy sauce",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "3 tbsp",    "item": "honey",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "brown sugar",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "orange zest",                   "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",                "store_section": "Produce"},
   {"amount": "1 tsp",     "item": "fresh ginger, grated",          "store_section": "Produce"},
   {"amount": "1 tbsp",    "item": "cornstarch mixed with 2 tbsp water", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Dip chicken in beaten egg then toss in cornstarch to coat.",
   "Fry in 2 inches of oil at 375°F until golden and crispy, about 4-5 minutes. Drain.",
   "Whisk orange juice, soy sauce, honey, brown sugar, zest, garlic, and ginger in a saucepan.",
   "Bring to a simmer over medium heat. Add cornstarch slurry and stir until thickened.",
   "Toss fried chicken in orange sauce immediately before serving.",
   "Serve over steamed rice with sesame seeds and green onions.",
 ],
 "substitutions": {
   "gluten_free": "Use tamari and gluten-free cornstarch.",
   "dairy_free": "Already dairy-free.",
   "low_carb": "Serve over cauliflower rice and reduce orange juice to 1/4 cup.",
 }},

{"name": "Pork Belly Ramen",
 "meal_type": "Dinner", "servings": 4, "prep_time": "20 minutes", "cook_time": "2 hours 30 minutes",
 "macros_per_serving": {"calories": 620, "protein_g": 28, "carbs_g": 58, "fat_g": 28},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "pork belly",                   "store_section": "Meat/Seafood"},
   {"amount": "4 portions","item": "ramen noodles",                "store_section": "Pantry/Dry Goods"},
   {"amount": "6 cups",    "item": "chicken broth",                "store_section": "Pantry/Dry Goods"},
   {"amount": "4",         "item": "soft-boiled eggs",             "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "soy sauce",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "mirin",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "sesame oil",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "4 cloves",  "item": "garlic, smashed",              "store_section": "Produce"},
   {"amount": "1 tbsp",    "item": "fresh ginger, sliced",         "store_section": "Produce"},
   {"amount": "4",         "item": "green onions, sliced",         "store_section": "Produce"},
   {"amount": "2 sheets",  "item": "nori (dried seaweed)",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "white miso paste",             "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Score pork belly skin. Roast skin-side up at 300°F for 2 hours until very tender. Rest 15 minutes.",
   "Slice pork belly into 1/2-inch rounds. Sear in a hot pan until caramelized.",
   "Bring broth, soy sauce, mirin, garlic, and ginger to a simmer for 20 minutes.",
   "Whisk miso paste into broth. Add sesame oil.",
   "Cook ramen noodles according to package directions.",
   "Soft boil eggs: 6.5 minutes in boiling water, then ice bath. Peel and halve.",
   "Assemble bowls: noodles, broth, pork belly slices, egg, green onions, and nori.",
 ],
 "substitutions": {
   "gluten_free": "Use rice noodles and tamari instead of soy sauce.",
   "dairy_free": "Already dairy-free.",
 },
 "notes": "Worth the time investment. Broth can be made a day ahead and reheated."},

{"name": "Pot Roast",
 "meal_type": "Dinner", "servings": 8, "prep_time": "20 minutes", "cook_time": "3 hours 30 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 42, "carbs_g": 22, "fat_g": 24},
 "ingredients": [
   {"amount": "4 lbs",     "item": "chuck roast",                  "store_section": "Meat/Seafood"},
   {"amount": "4",         "item": "large carrots, cut into chunks","store_section": "Produce"},
   {"amount": "4",         "item": "russet potatoes, quartered",   "store_section": "Produce"},
   {"amount": "1 large",   "item": "onion, quartered",             "store_section": "Produce"},
   {"amount": "4 cloves",  "item": "garlic, smashed",              "store_section": "Produce"},
   {"amount": "2 cups",    "item": "beef broth",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "red wine (optional)",          "store_section": "Beverages"},
   {"amount": "2 tbsp",    "item": "Worcestershire sauce",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 sprigs",  "item": "fresh rosemary",               "store_section": "Produce"},
   {"amount": "2 sprigs",  "item": "fresh thyme",                  "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "vegetable oil",                "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 325°F. Pat roast dry and season heavily with salt and pepper.",
   "Heat oil in a Dutch oven over high heat. Sear roast 4 minutes per side until deep brown.",
   "Remove roast. Saute onion and garlic 3 minutes.",
   "Add broth, wine, and Worcestershire. Bring to a simmer, scraping up browned bits.",
   "Return roast. Add rosemary and thyme. Cover tightly.",
   "Braise in oven 2.5 hours. Add carrots and potatoes. Cook 1 more hour.",
   "Rest 15 minutes. Shred or slice and serve with braising liquid as gravy.",
 ],
 "substitutions": {
   "gluten_free": "Already gluten-free.",
   "dairy_free": "Already dairy-free.",
   "low_carb": "Skip potatoes and serve with cauliflower mash.",
 },
 "notes": "The deeper the sear, the richer the final flavor. Don't rush that step."},

{"name": "Shepherd's Pie",
 "meal_type": "Dinner", "servings": 6, "prep_time": "20 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 28, "carbs_g": 38, "fat_g": 16},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "ground lamb or beef",          "store_section": "Meat/Seafood"},
   {"amount": "2 lbs",     "item": "russet potatoes, peeled",      "store_section": "Produce"},
   {"amount": "1 large",   "item": "onion, diced",                 "store_section": "Produce"},
   {"amount": "2",         "item": "carrots, diced",               "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1 cup",     "item": "frozen peas",                  "store_section": "Frozen"},
   {"amount": "1 cup",     "item": "beef broth",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "Worcestershire sauce",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "tomato paste",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "4 tbsp",    "item": "butter",                       "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "milk or cream",                "store_section": "Dairy/Eggs"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Boil potatoes until tender. Drain and mash with butter and milk. Season with salt and pepper.",
   "Preheat oven to 400°F.",
   "Brown meat in a skillet. Add onion, carrots, and garlic. Cook 5 minutes.",
   "Stir in tomato paste, Worcestershire, and broth. Simmer 8 minutes until thickened.",
   "Stir in frozen peas. Season with salt and pepper.",
   "Transfer meat mixture to a baking dish. Spread mashed potatoes evenly over the top.",
   "Bake 20-25 minutes until top is golden. Rest 5 minutes before serving.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and oat milk in the mash.",
   "gluten_free": "Already gluten-free.",
   "vegetarian": "Use lentils instead of meat and vegetable broth.",
 }},

{"name": "Shrimp Scampi",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 32, "carbs_g": 48, "fat_g": 18},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "large shrimp, peeled and deveined","store_section": "Meat/Seafood"},
   {"amount": "12 oz",     "item": "linguine pasta",               "store_section": "Pantry/Dry Goods"},
   {"amount": "6 cloves",  "item": "garlic, thinly sliced",        "store_section": "Produce"},
   {"amount": "1/2 cup",   "item": "dry white wine",               "store_section": "Beverages"},
   {"amount": "1/2 cup",   "item": "chicken broth",                "store_section": "Pantry/Dry Goods"},
   {"amount": "4 tbsp",    "item": "butter",                       "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",   "item": "red pepper flakes",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2",       "item": "lemon, juiced and zested",     "store_section": "Produce"},
   {"amount": "1/4 cup",   "item": "fresh parsley, chopped",       "store_section": "Produce"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook linguine until al dente. Reserve 1 cup pasta water. Drain.",
   "Heat olive oil in a large skillet over medium-high heat. Cook shrimp 1-2 minutes per side until pink. Remove.",
   "Add garlic and red pepper flakes. Cook 1 minute.",
   "Pour in wine and broth. Simmer 3 minutes.",
   "Add butter and lemon juice. Swirl until butter melts.",
   "Add pasta and toss, adding pasta water to loosen as needed.",
   "Return shrimp. Toss and top with parsley and lemon zest.",
 ],
 "substitutions": {
   "dairy_free": "Replace butter with olive oil.",
   "gluten_free": "Use gluten-free pasta.",
   "low_carb": "Serve over zucchini noodles.",
 }},

{"name": "Stuffed Zucchini Boats",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 320, "protein_g": 22, "carbs_g": 18, "fat_g": 18},
 "ingredients": [
   {"amount": "4 large",   "item": "zucchini",                     "store_section": "Produce"},
   {"amount": "1 lb",      "item": "ground beef or Italian sausage","store_section": "Meat/Seafood"},
   {"amount": "1 large",   "item": "onion, diced",                 "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1/2 cup",   "item": "marinara sauce",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "shredded mozzarella",          "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",   "item": "grated parmesan",              "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "Italian seasoning",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 400°F.",
   "Halve zucchini lengthwise. Scoop out flesh, leaving a 1/4-inch shell. Chop flesh and set aside.",
   "Brush zucchini shells with olive oil, season, and bake cut-side down 10 minutes.",
   "Brown meat with onion and garlic. Add chopped zucchini flesh and cook 3 minutes.",
   "Stir in marinara, Italian seasoning, salt, and pepper.",
   "Fill zucchini shells with meat mixture. Top with mozzarella and parmesan.",
   "Bake 15-18 minutes until cheese is bubbly and golden.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cheese.",
   "gluten_free": "Already gluten-free.",
   "vegetarian": "Replace meat with cooked quinoa and black beans.",
   "low_carb": "Already low-carb.",
 }},

]

for r in recipes:
    fn = r['name'].lower().replace(' ', '-').replace('&', 'and').replace("'", '').replace(',', '') + '.json'
    (OUT / fn).write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {fn}')
print(f'Done — {len(recipes)} dinner recipes (batch 2).')
