#!/usr/bin/env python3
"""Add 10 new dessert recipes."""
import json
from pathlib import Path

OUT = Path(__file__).parent / 'data'

desserts = [

{"name": "No-Bake Chocolate Oatmeal Cookies",
 "meal_type": "Desserts", "servings": 24, "prep_time": "5 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 140, "protein_g": 2, "carbs_g": 20, "fat_g": 6},
 "ingredients": [
   {"amount": "2 cups",  "item": "granulated sugar",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup", "item": "butter",                   "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup", "item": "milk",                     "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup", "item": "unsweetened cocoa powder", "store_section": "Pantry/Dry Goods"},
   {"amount": "3 cups",  "item": "quick oats",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup", "item": "peanut butter",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",   "item": "vanilla extract",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp", "item": "salt",                     "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Line two baking sheets with parchment paper.",
   "Combine sugar, butter, milk, and cocoa powder in a saucepan over medium heat.",
   "Bring to a rolling boil, stirring constantly. Boil exactly 1 minute — no more.",
   "Remove from heat. Quickly stir in peanut butter and vanilla until smooth.",
   "Fold in oats and salt. Mix well.",
   "Drop heaping tablespoons onto prepared baking sheets.",
   "Let cool and set at room temperature, about 30 minutes. Do not refrigerate while setting.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and oat milk.",
   "gluten_free": "Use certified gluten-free quick oats.",
   "vegan": "Use dairy-free butter and plant milk.",
 },
 "notes": "The 1-minute boil is critical — too short and they won't set, too long and they go crumbly."},

{"name": "Fudgy Brownies",
 "meal_type": "Desserts", "servings": 16, "prep_time": "15 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 220, "protein_g": 3, "carbs_g": 28, "fat_g": 12},
 "ingredients": [
   {"amount": "1 cup",    "item": "butter",                    "store_section": "Dairy/Eggs"},
   {"amount": "2 cups",   "item": "granulated sugar",          "store_section": "Pantry/Dry Goods"},
   {"amount": "4 large",  "item": "eggs",                      "store_section": "Dairy/Eggs"},
   {"amount": "2 tsp",    "item": "vanilla extract",           "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",  "item": "unsweetened cocoa powder",  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "all-purpose flour",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "salt",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",  "item": "baking powder",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "chocolate chips",           "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease a 9x13 inch baking pan.",
   "Melt butter in a large saucepan over medium heat. Remove from heat.",
   "Stir in sugar, eggs, and vanilla until well combined.",
   "Add cocoa powder, flour, salt, and baking powder. Mix until just combined.",
   "Fold in chocolate chips.",
   "Spread batter evenly into prepared pan.",
   "Bake 20-25 minutes until a toothpick comes out with a few moist crumbs.",
   "Cool completely in pan before cutting.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and dairy-free chocolate chips.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use vegan butter and replace each egg with a flax egg.",
 },
 "notes": "Underbake slightly for fudgy centers — they continue cooking in the pan."},

{"name": "Apple Crisp",
 "meal_type": "Desserts", "servings": 8, "prep_time": "15 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 3, "carbs_g": 48, "fat_g": 10},
 "ingredients": [
   {"amount": "6 large",  "item": "apples, peeled and sliced thin", "store_section": "Produce"},
   {"amount": "2 tbsp",   "item": "granulated sugar",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",    "item": "cinnamon",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",   "item": "lemon juice",                    "store_section": "Produce"},
   {"amount": "1 cup",    "item": "rolled oats",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "all-purpose flour",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "brown sugar, packed",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "cinnamon",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",  "item": "salt",                           "store_section": "Pantry/Dry Goods"},
   {"amount": "6 tbsp",   "item": "cold butter, cubed",             "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Preheat oven to 375°F. Butter a 9x13 inch baking dish.",
   "Toss apple slices with granulated sugar, 1 tsp cinnamon, and lemon juice. Spread in dish.",
   "Mix oats, flour, brown sugar, remaining cinnamon, and salt in a bowl.",
   "Cut in cold butter with your fingers until the mixture resembles coarse crumbs.",
   "Spread topping evenly over apples.",
   "Bake 40-45 minutes until topping is golden and apples are bubbling.",
   "Serve warm with vanilla ice cream or whipped cream.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and coconut whipped cream.",
   "gluten_free": "Use gluten-free oats and a 1:1 gluten-free flour blend.",
   "vegan": "Use coconut oil instead of butter.",
 },
 "notes": "Granny Smith apples hold their shape best. Honeycrisp gives a sweeter result."},

{"name": "Peach Cobbler",
 "meal_type": "Desserts", "servings": 8, "prep_time": "10 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 300, "protein_g": 4, "carbs_g": 50, "fat_g": 10},
 "ingredients": [
   {"amount": "2 cans",   "item": "sliced peaches in juice (15 oz each)", "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "all-purpose flour",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "granulated sugar",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "milk",                                  "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",  "item": "butter",                                "store_section": "Dairy/Eggs"},
   {"amount": "2 tsp",    "item": "baking powder",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "cinnamon",                              "store_section": "Pantry/Dry Goods"},
   {"amount": "pinch",    "item": "salt",                                  "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F.",
   "Melt butter in a 9x13 inch baking dish in the oven, about 5 minutes. Remove from oven.",
   "Whisk flour, sugar, baking powder, cinnamon, and salt together.",
   "Stir in milk until a smooth batter forms.",
   "Pour batter over melted butter — do not stir.",
   "Spoon peaches with their juice over the batter — do not stir.",
   "Bake 40-45 minutes until top is golden brown and edges are bubbling.",
   "Serve warm with ice cream.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk and dairy-free butter.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use plant milk and vegan butter.",
 },
 "notes": "Do not stir after adding butter, batter, or peaches — the layers self-sort during baking."},

{"name": "Rice Krispie Treats",
 "meal_type": "Desserts", "servings": 16, "prep_time": "5 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 160, "protein_g": 1, "carbs_g": 30, "fat_g": 5},
 "ingredients": [
   {"amount": "6 cups",   "item": "Rice Krispies cereal",    "store_section": "Pantry/Dry Goods"},
   {"amount": "4 tbsp",   "item": "butter",                  "store_section": "Dairy/Eggs"},
   {"amount": "10 oz",    "item": "mini marshmallows",        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",    "item": "vanilla extract",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",  "item": "salt",                     "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Grease a 9x13 inch pan with butter.",
   "Melt butter in a large pot over low heat.",
   "Add marshmallows and stir until completely melted. Remove from heat.",
   "Stir in vanilla and salt.",
   "Add Rice Krispies and fold until fully coated.",
   "Press mixture firmly into prepared pan using a buttered spatula.",
   "Let cool 30 minutes before cutting into squares.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter.",
   "gluten_free": "Already gluten-free.",
   "vegan": "Use vegan butter and vegan marshmallows.",
 },
 "notes": "Use low heat and don't overcook — brown butter makes them chewy instead of gooey."},

{"name": "Peanut Butter Fudge",
 "meal_type": "Desserts", "servings": 36, "prep_time": "10 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 130, "protein_g": 3, "carbs_g": 16, "fat_g": 7},
 "ingredients": [
   {"amount": "2 cups",   "item": "granulated sugar",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "milk",                     "store_section": "Dairy/Eggs"},
   {"amount": "1/4 tsp",  "item": "salt",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "peanut butter",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",    "item": "vanilla extract",          "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",   "item": "butter",                   "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Line an 8x8 inch pan with parchment paper.",
   "Combine sugar, milk, and salt in a saucepan over medium heat.",
   "Bring to a boil, stirring constantly. Boil exactly 2.5 minutes without stirring.",
   "Remove from heat. Stir in peanut butter, vanilla, and butter until smooth.",
   "Quickly pour into prepared pan and spread evenly.",
   "Let set at room temperature 2 hours or refrigerate 1 hour.",
   "Lift out using parchment and cut into small squares.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk and dairy-free butter.",
   "gluten_free": "Already gluten-free.",
   "vegan": "Use plant milk and vegan butter.",
 },
 "notes": "Move fast once off the heat — it sets quickly. Have your pan ready before you start."},

{"name": "Lemon Bars",
 "meal_type": "Desserts", "servings": 16, "prep_time": "20 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 200, "protein_g": 3, "carbs_g": 30, "fat_g": 9},
 "ingredients": [
   {"amount": "1 cup",    "item": "all-purpose flour",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",  "item": "powdered sugar",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "cold butter, cubed",        "store_section": "Dairy/Eggs"},
   {"amount": "1/4 tsp",  "item": "salt",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "4 large",  "item": "eggs",                      "store_section": "Dairy/Eggs"},
   {"amount": "1.5 cups", "item": "granulated sugar",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "fresh lemon juice (3-4 lemons)", "store_section": "Produce"},
   {"amount": "2 tbsp",   "item": "lemon zest",                "store_section": "Produce"},
   {"amount": "1/4 cup",  "item": "all-purpose flour",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",   "item": "powdered sugar for dusting","store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease an 8x8 inch pan.",
   "Mix 1 cup flour, 1/4 cup powdered sugar, and salt. Cut in cold butter until crumbly.",
   "Press crust firmly into the bottom of prepared pan.",
   "Bake crust 15-18 minutes until lightly golden.",
   "Whisk eggs, granulated sugar, lemon juice, lemon zest, and 1/4 cup flour until smooth.",
   "Pour filling over hot crust.",
   "Bake 20-25 minutes until filling is set and no longer jiggly.",
   "Cool completely then dust with powdered sugar before cutting.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter in the crust.",
   "gluten_free": "Use a 1:1 gluten-free flour blend for both crust and filling.",
 },
 "notes": "Pour filling over the hot crust — this helps it bond and prevents a soggy bottom."},

{"name": "Strawberry Shortcake",
 "meal_type": "Desserts", "servings": 8, "prep_time": "20 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 340, "protein_g": 5, "carbs_g": 44, "fat_g": 16},
 "ingredients": [
   {"amount": "2 lbs",    "item": "fresh strawberries, sliced",   "store_section": "Produce"},
   {"amount": "3 tbsp",   "item": "granulated sugar",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",   "item": "all-purpose flour",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",   "item": "sugar",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",   "item": "baking powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "salt",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "cold butter, cubed",           "store_section": "Dairy/Eggs"},
   {"amount": "3/4 cup",  "item": "heavy cream",                  "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",    "item": "heavy cream, whipped",         "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Toss sliced strawberries with 3 tbsp sugar. Let sit 30 minutes to macerate.",
   "Preheat oven to 425°F. Line a baking sheet with parchment.",
   "Mix flour, 2 tbsp sugar, baking powder, and salt.",
   "Cut in cold butter until mixture resembles coarse crumbs.",
   "Stir in heavy cream until dough just comes together.",
   "Drop 8 mounds onto prepared sheet. Bake 12-15 minutes until golden.",
   "Split shortcakes in half. Top with strawberries and whipped cream.",
 ],
 "substitutions": {
   "dairy_free": "Use coconut cream (chilled and whipped) and dairy-free butter.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use coconut oil and chilled coconut cream.",
 }},

{"name": "Cinnamon Sugar Donuts",
 "meal_type": "Desserts", "servings": 12, "prep_time": "10 minutes", "cook_time": "12 minutes",
 "macros_per_serving": {"calories": 210, "protein_g": 4, "carbs_g": 32, "fat_g": 8},
 "ingredients": [
   {"amount": "2 cups",   "item": "all-purpose flour",        "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",  "item": "granulated sugar",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",    "item": "baking powder",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "cinnamon",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "nutmeg",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "salt",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",  "item": "milk",                     "store_section": "Dairy/Eggs"},
   {"amount": "2 large",  "item": "eggs",                     "store_section": "Dairy/Eggs"},
   {"amount": "4 tbsp",   "item": "butter, melted",           "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",    "item": "vanilla extract",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "granulated sugar (coating)","store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",    "item": "cinnamon (coating)",       "store_section": "Pantry/Dry Goods"},
   {"amount": "4 tbsp",   "item": "butter, melted (coating)", "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Preheat oven to 400°F. Grease a donut pan.",
   "Whisk flour, sugar, baking powder, cinnamon, nutmeg, and salt in a large bowl.",
   "In another bowl, whisk milk, eggs, melted butter, and vanilla.",
   "Pour wet ingredients into dry and stir until just combined.",
   "Pipe or spoon batter into donut pan, filling 3/4 full.",
   "Bake 10-12 minutes until donuts spring back when touched.",
   "Mix 1/2 cup sugar with 1 tsp cinnamon in a shallow bowl.",
   "Brush warm donuts with melted butter, then roll in cinnamon sugar.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk and dairy-free butter.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use oat milk, vegan butter, and flax eggs.",
 },
 "notes": "A donut pan is required. Do not overbake — they dry out quickly."},

{"name": "Monkey Bread",
 "meal_type": "Desserts", "servings": 10, "prep_time": "15 minutes", "cook_time": "35 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 6, "carbs_g": 62, "fat_g": 16},
 "ingredients": [
   {"amount": "3 cans",   "item": "refrigerated biscuit dough (7.5 oz each)", "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",    "item": "granulated sugar",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",    "item": "cinnamon",                                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",    "item": "brown sugar, packed",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",  "item": "butter",                                    "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",    "item": "vanilla extract",                           "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Grease a bundt pan.",
   "Mix granulated sugar and cinnamon in a zip-top bag.",
   "Cut each biscuit into quarters. Toss pieces in cinnamon sugar to coat. Layer in bundt pan.",
   "Melt butter in a saucepan with brown sugar and vanilla. Bring to a boil and cook 1 minute.",
   "Pour brown butter sauce over biscuit pieces.",
   "Bake 30-35 minutes until deep golden brown and cooked through.",
   "Cool in pan 10 minutes then invert onto a serving plate. Pull apart to serve.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter.",
   "vegan": "Use dairy-free biscuit dough and vegan butter.",
 },
 "notes": "Do not skip the 10-minute rest before inverting — the caramel needs to set slightly."},

]

saved = 0
for r in desserts:
    filename = r['name'].lower().replace(' ', '-').replace("'", '').replace(',', '') + '.json'
    p = OUT / filename
    p.write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {filename}')
    saved += 1

print(f'\nDone — {saved} desserts saved.')
