#!/usr/bin/env python3
import json
from pathlib import Path
OUT = Path(__file__).parent / 'data'

recipes = [

{"name": "Beef and Broccoli",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 38, "carbs_g": 28, "fat_g": 16},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "flank steak, thinly sliced",   "store_section": "Meat/Seafood"},
   {"amount": "4 cups",    "item": "broccoli florets",              "store_section": "Produce"},
   {"amount": "1/3 cup",   "item": "soy sauce",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "3 tbsp",    "item": "oyster sauce",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "brown sugar",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "sesame oil",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "4 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1 tsp",     "item": "fresh ginger, grated",         "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "cornstarch",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "vegetable oil",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/3 cup",   "item": "beef broth",                   "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Toss sliced beef with 1 tbsp cornstarch, salt, and a splash of soy sauce. Set aside.",
   "Whisk together soy sauce, oyster sauce, brown sugar, sesame oil, remaining cornstarch, and beef broth.",
   "Heat oil in a wok over high heat. Sear beef in batches until browned. Remove and set aside.",
   "Add broccoli and stir fry 3-4 minutes until tender-crisp.",
   "Add garlic and ginger, cook 30 seconds.",
   "Return beef to wok. Pour sauce over everything and toss until thickened, 2 minutes.",
   "Serve over steamed rice.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use tamari and gluten-free oyster sauce.",
   "low_carb": "Serve over cauliflower rice.",
 }},

{"name": "Beef Enchiladas",
 "meal_type": "Dinner", "servings": 6, "prep_time": "20 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 32, "carbs_g": 42, "fat_g": 18},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "ground beef",                  "store_section": "Meat/Seafood"},
   {"amount": "12",        "item": "corn tortillas",               "store_section": "Bakery"},
   {"amount": "2 cans",    "item": "red enchilada sauce (10 oz each)", "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",    "item": "shredded Mexican cheese blend","store_section": "Dairy/Eggs"},
   {"amount": "1 large",   "item": "onion, diced",                 "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1 can",     "item": "black beans, drained",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",     "item": "cumin",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",     "item": "chili powder",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 375°F.",
   "Brown ground beef with onion and garlic. Drain fat. Add cumin, chili powder, salt, and beans.",
   "Pour 1/2 cup enchilada sauce in the bottom of a 9x13 baking dish.",
   "Warm tortillas briefly so they roll without cracking.",
   "Fill each tortilla with 3 tbsp of beef mixture, roll tightly, and place seam-side down in dish.",
   "Pour remaining enchilada sauce over top. Sprinkle with cheese.",
   "Bake 25-30 minutes until cheese is melted and bubbly.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cheese.",
   "gluten_free": "Corn tortillas are naturally gluten-free.",
   "vegetarian": "Replace beef with a mix of black beans and corn.",
 }},

{"name": "Beef Stroganoff",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 560, "protein_g": 38, "carbs_g": 48, "fat_g": 22},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "sirloin steak, thinly sliced",  "store_section": "Meat/Seafood"},
   {"amount": "12 oz",     "item": "egg noodles",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 large",   "item": "onion, diced",                  "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",                "store_section": "Produce"},
   {"amount": "2 cups",    "item": "beef broth",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "sour cream",                    "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "Worcestershire sauce",          "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "all-purpose flour",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "butter",                        "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "olive oil",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",               "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook egg noodles according to package directions. Drain and set aside.",
   "Season steak with salt and pepper. Sear in hot oil in batches until browned. Remove and set aside.",
   "Melt butter in the same pan. Saute onion 5 minutes. Add garlic and cook 1 minute.",
   "Sprinkle in flour and stir 2 minutes.",
   "Pour in beef broth and Worcestershire sauce. Bring to a simmer, scraping up any browned bits.",
   "Reduce heat to low. Stir in sour cream until smooth — do not boil.",
   "Return beef to pan and heat through. Serve over egg noodles.",
 ],
 "substitutions": {
   "dairy_free": "Replace sour cream with full-fat coconut cream.",
   "gluten_free": "Use gluten-free pasta and cornstarch instead of flour.",
   "low_carb": "Serve over zucchini noodles instead of egg noodles.",
 },
 "notes": "Never boil after adding sour cream or it will curdle."},

{"name": "Cajun Shrimp Pasta",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 520, "protein_g": 32, "carbs_g": 56, "fat_g": 18},
 "ingredients": [
   {"amount": "1 lb",      "item": "large shrimp, peeled and deveined","store_section": "Meat/Seafood"},
   {"amount": "12 oz",     "item": "penne or fettuccine pasta",        "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "Cajun seasoning",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "4 cloves",  "item": "garlic, minced",                   "store_section": "Produce"},
   {"amount": "1 cup",     "item": "heavy cream",                      "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "chicken broth",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "grated parmesan",                  "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "butter",                           "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "olive oil",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "fresh",     "item": "parsley for garnish",              "store_section": "Produce"},
 ],
 "instructions": [
   "Cook pasta according to package directions. Reserve 1/2 cup pasta water before draining.",
   "Toss shrimp with Cajun seasoning.",
   "Heat olive oil in a large skillet over high heat. Cook shrimp 1-2 minutes per side. Remove.",
   "Reduce heat to medium. Melt butter and saute garlic 1 minute.",
   "Add cream and broth. Simmer 5 minutes until slightly reduced.",
   "Stir in parmesan until melted. Add pasta and toss, using pasta water to loosen if needed.",
   "Top with shrimp and parsley. Serve immediately.",
 ],
 "substitutions": {
   "dairy_free": "Use coconut cream and nutritional yeast instead of cream and parmesan.",
   "gluten_free": "Use gluten-free pasta.",
   "low_carb": "Serve over zucchini noodles.",
 }},

{"name": "Chicken Marsala",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 38, "carbs_g": 18, "fat_g": 20},
 "ingredients": [
   {"amount": "4",         "item": "chicken breasts, pounded thin",  "store_section": "Meat/Seafood"},
   {"amount": "1/2 cup",   "item": "all-purpose flour",              "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",   "item": "Marsala wine",                   "store_section": "Beverages"},
   {"amount": "1 cup",     "item": "chicken broth",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "heavy cream",                    "store_section": "Dairy/Eggs"},
   {"amount": "1 large",   "item": "onion, thinly sliced",           "store_section": "Produce"},
   {"amount": "4 cloves",  "item": "garlic, minced",                 "store_section": "Produce"},
   {"amount": "3 tbsp",    "item": "butter",                         "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "olive oil",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "fresh",     "item": "parsley for garnish",            "store_section": "Produce"},
   {"amount": "to taste",  "item": "salt and pepper",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season chicken with salt and pepper. Dredge in flour, shaking off excess.",
   "Heat oil in a large skillet over medium-high heat. Cook chicken 4-5 minutes per side until golden.",
   "Remove chicken. Add butter, onion, and garlic to pan. Cook 5 minutes.",
   "Pour in Marsala wine, scraping up browned bits. Simmer 3 minutes.",
   "Add broth and cream. Simmer 8 minutes until sauce thickens.",
   "Return chicken to pan and coat in sauce. Simmer 3 more minutes.",
   "Garnish with parsley. Serve with mashed potatoes or pasta.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter and coconut cream.",
   "gluten_free": "Use rice flour for dredging and gluten-free pasta on the side.",
   "low_carb": "Serve over cauliflower mash.",
 },
 "notes": "Traditional Marsala uses mushrooms — swapped here for onion to keep the sauce rich."},

{"name": "Chicken Parmesan",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 580, "protein_g": 48, "carbs_g": 38, "fat_g": 22},
 "ingredients": [
   {"amount": "4",         "item": "chicken breasts, pounded thin","store_section": "Meat/Seafood"},
   {"amount": "1 cup",     "item": "Italian breadcrumbs",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "grated parmesan",              "store_section": "Dairy/Eggs"},
   {"amount": "2 large",   "item": "eggs, beaten",                 "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "all-purpose flour",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 cups",  "item": "marinara sauce",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 cups",  "item": "shredded mozzarella",          "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 400°F.",
   "Set up a breading station: flour, beaten eggs, breadcrumbs mixed with parmesan.",
   "Season chicken with salt and pepper. Coat in flour, then egg, then breadcrumb mixture.",
   "Heat olive oil in an oven-safe skillet. Fry chicken 3-4 minutes per side until golden.",
   "Top each piece with marinara sauce and mozzarella.",
   "Transfer to oven and bake 15-18 minutes until cheese is bubbly and chicken is cooked through.",
   "Serve over spaghetti or with garlic bread.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free breadcrumbs and mozzarella.",
   "gluten_free": "Use gluten-free breadcrumbs and flour.",
   "low_carb": "Use crushed pork rinds instead of breadcrumbs.",
 }},

{"name": "Classic Beef Burgers",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "12 minutes",
 "macros_per_serving": {"calories": 620, "protein_g": 38, "carbs_g": 42, "fat_g": 32},
 "ingredients": [
   {"amount": "2 lbs",     "item": "80/20 ground beef",            "store_section": "Meat/Seafood"},
   {"amount": "4",         "item": "brioche burger buns",          "store_section": "Bakery"},
   {"amount": "4 slices",  "item": "American or cheddar cheese",   "store_section": "Dairy/Eggs"},
   {"amount": "4 leaves",  "item": "iceberg lettuce",              "store_section": "Produce"},
   {"amount": "1/4 cup",   "item": "mayonnaise",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "ketchup",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "yellow mustard",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2",       "item": "onion, thinly sliced",         "store_section": "Produce"},
   {"amount": "8 slices",  "item": "dill pickles",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Divide beef into 4 equal portions. Shape into patties slightly wider than the buns.",
   "Make a small indent in the center of each patty — prevents puffing.",
   "Season generously with salt and pepper on both sides.",
   "Cook on a hot grill or cast iron skillet 4-5 minutes per side for medium.",
   "Add cheese in the last minute. Cover to melt.",
   "Mix mayo, ketchup, and mustard for the burger sauce. Toast buns.",
   "Build burgers: bun, sauce, lettuce, patty, onion, pickles, top bun.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free slices.",
   "gluten_free": "Use a gluten-free bun.",
   "low_carb": "Serve in lettuce wraps.",
 },
 "notes": "80/20 fat ratio gives the best flavor and juiciness. Do not press the patty while cooking."},

{"name": "Coconut Curry Shrimp",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 28, "carbs_g": 28, "fat_g": 16},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "large shrimp, peeled and deveined","store_section": "Meat/Seafood"},
   {"amount": "1 can",     "item": "coconut milk (13.5 oz)",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 large",   "item": "onion, diced",                      "store_section": "Produce"},
   {"amount": "4 cloves",  "item": "garlic, minced",                    "store_section": "Produce"},
   {"amount": "1 tbsp",    "item": "fresh ginger, grated",              "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "red curry paste",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "fish sauce",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "brown sugar",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "coconut oil",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "fresh",     "item": "cilantro and lime for serving",     "store_section": "Produce"},
 ],
 "instructions": [
   "Heat coconut oil in a large skillet over medium heat.",
   "Saute onion 5 minutes. Add garlic and ginger, cook 1 minute.",
   "Add curry paste and stir 1 minute until fragrant.",
   "Pour in coconut milk. Stir in fish sauce and brown sugar.",
   "Simmer 8 minutes until sauce thickens slightly.",
   "Add shrimp and cook 3-4 minutes until pink and cooked through.",
   "Serve over jasmine rice with cilantro and lime wedges.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use gluten-free fish sauce or coconut aminos.",
   "low_carb": "Serve over cauliflower rice.",
   "vegetarian": "Replace shrimp with chickpeas and extra vegetables.",
 }},

{"name": "Coconut Shrimp",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 320, "protein_g": 22, "carbs_g": 28, "fat_g": 14},
 "ingredients": [
   {"amount": "1.5 lbs",   "item": "large shrimp, peeled and deveined","store_section": "Meat/Seafood"},
   {"amount": "1.5 cups",  "item": "shredded sweetened coconut",       "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "panko breadcrumbs",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "all-purpose flour",                "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",   "item": "eggs, beaten",                     "store_section": "Dairy/Eggs"},
   {"amount": "oil",       "item": "for frying",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "sweet chili sauce for dipping",    "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Pat shrimp dry. Season with salt and pepper.",
   "Set up breading station: flour, beaten eggs, coconut mixed with panko.",
   "Coat each shrimp: flour, egg, coconut-panko mixture. Press to adhere.",
   "Heat 2 inches of oil to 350°F in a heavy pot.",
   "Fry shrimp in batches 2-3 minutes until golden and coconut is toasted.",
   "Drain on paper towels. Serve immediately with sweet chili sauce.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use rice flour and gluten-free panko.",
   "baked": "Bake at 400°F on a greased rack 10-12 minutes, flipping halfway.",
 }},

{"name": "Creamy Tuscan Chicken",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 42, "carbs_g": 12, "fat_g": 28},
 "ingredients": [
   {"amount": "4",         "item": "chicken breasts",              "store_section": "Meat/Seafood"},
   {"amount": "1 cup",     "item": "heavy cream",                  "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "chicken broth",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "grated parmesan",              "store_section": "Dairy/Eggs"},
   {"amount": "4 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "1/3 cup",   "item": "sun-dried tomatoes, chopped",  "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",    "item": "fresh spinach",                "store_section": "Produce"},
   {"amount": "1 tsp",     "item": "Italian seasoning",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season chicken with Italian seasoning, salt, and pepper.",
   "Heat oil in a large skillet over medium-high heat. Cook chicken 6-7 minutes per side until cooked through. Remove.",
   "In the same pan, saute garlic 1 minute. Add sun-dried tomatoes and cook 1 minute.",
   "Pour in broth and cream. Simmer 5 minutes.",
   "Stir in parmesan until melted. Add spinach and cook until wilted.",
   "Return chicken to pan and coat in sauce. Simmer 3 minutes.",
   "Serve over pasta, rice, or with crusty bread.",
 ],
 "substitutions": {
   "dairy_free": "Use coconut cream and nutritional yeast.",
   "gluten_free": "Already gluten-free — serve with gluten-free pasta.",
   "low_carb": "Serve over zucchini noodles or cauliflower rice.",
 }},

]

for r in recipes:
    fn = r['name'].lower().replace(' ', '-').replace('&', 'and').replace("'", '').replace(',', '') + '.json'
    (OUT / fn).write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {fn}')
print(f'Done — {len(recipes)} dinner recipes (batch 1).')
