#!/usr/bin/env python3
import json
from pathlib import Path
OUT = Path(__file__).parent / 'data'

recipes = [

{"name": "Chicken Tortilla Soup",
 "meal_type": "Lunch", "servings": 6, "prep_time": "10 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 360, "protein_g": 28, "carbs_g": 32, "fat_g": 12},
 "ingredients": [
   {"amount": "2",         "item": "chicken breasts",              "store_section": "Meat/Seafood"},
   {"amount": "1 can",     "item": "black beans, drained (15 oz)", "store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",     "item": "corn, drained (15 oz)",        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",     "item": "enchilada sauce (10 oz)",      "store_section": "Pantry/Dry Goods"},
   {"amount": "4 cups",    "item": "chicken broth",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 large",   "item": "onion, diced",                 "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "2 tsp",     "item": "cumin",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",     "item": "chili powder",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "for topping","item": "shredded cheese, sour cream, tortilla strips", "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Heat olive oil in a large pot. Saute onion 5 minutes. Add garlic, cumin, and chili powder, cook 1 minute.",
   "Add chicken breasts, broth, enchilada sauce, beans, and corn.",
   "Bring to a boil, reduce heat and simmer 20 minutes until chicken is cooked through.",
   "Remove chicken, shred with two forks, and return to pot.",
   "Simmer 5 more minutes. Season with salt.",
   "Serve topped with shredded cheese, sour cream, and tortilla strips.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese and sour cream toppings.",
   "gluten_free": "Use gluten-free enchilada sauce and tortilla strips.",
   "vegetarian": "Replace chicken with an extra can of beans and use vegetable broth.",
 }},

{"name": "Cold Pasta Salad",
 "meal_type": "Lunch", "servings": 6, "prep_time": "15 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 14, "carbs_g": 48, "fat_g": 16},
 "ingredients": [
   {"amount": "1 lb",      "item": "rotini or penne pasta",        "store_section": "Pantry/Dry Goods"},
   {"amount": "4 oz",      "item": "salami, sliced into strips",   "store_section": "Meat/Seafood"},
   {"amount": "1 cup",     "item": "black olives, sliced",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "mozzarella balls or cubed",    "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "pepperoncini, sliced",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "red onion, thinly sliced",     "store_section": "Produce"},
   {"amount": "1/2 cup",   "item": "Italian dressing",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",   "item": "grated parmesan",              "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",     "item": "dried Italian seasoning",      "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook pasta according to package directions. Drain and rinse under cold water.",
   "Combine pasta, salami, olives, mozzarella, pepperoncini, and red onion in a large bowl.",
   "Pour Italian dressing over and toss to coat.",
   "Add parmesan and Italian seasoning. Toss again.",
   "Refrigerate at least 1 hour before serving. Toss again and adjust seasoning.",
 ],
 "substitutions": {
   "dairy_free": "Skip mozzarella and parmesan.",
   "gluten_free": "Use gluten-free pasta.",
   "vegetarian": "Skip salami and add artichoke hearts and extra olives.",
 },
 "notes": "Gets better overnight as flavors meld. Add a splash more dressing before serving if it seems dry."},

{"name": "Corn Chowder",
 "meal_type": "Lunch", "servings": 4, "prep_time": "10 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 340, "protein_g": 10, "carbs_g": 42, "fat_g": 16},
 "ingredients": [
   {"amount": "4 cups",    "item": "corn kernels (fresh or frozen)","store_section": "Frozen"},
   {"amount": "3",         "item": "russet potatoes, peeled and diced","store_section": "Produce"},
   {"amount": "1 large",   "item": "onion, diced",                 "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "4 strips",  "item": "bacon, diced",                 "store_section": "Meat/Seafood"},
   {"amount": "3 cups",    "item": "chicken broth",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "heavy cream",                  "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "butter",                       "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "all-purpose flour",            "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt, pepper, smoked paprika", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook bacon in a large pot until crispy. Remove and set aside, leaving drippings in pot.",
   "Add butter and saute onion 5 minutes. Add garlic and cook 1 minute.",
   "Whisk in flour and cook 2 minutes.",
   "Add broth and potatoes. Bring to a boil and cook 12 minutes until potatoes are tender.",
   "Add corn and cream. Simmer 8 minutes.",
   "Use an immersion blender to blend about half the soup for a creamy-chunky texture.",
   "Season with salt, pepper, and smoked paprika. Top with reserved bacon.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk and dairy-free butter.",
   "gluten_free": "Replace flour with 1 tbsp cornstarch.",
   "vegetarian": "Skip bacon, use vegetable broth, and add 1/2 tsp smoked paprika for depth.",
 }},

{"name": "Cuban Sandwich",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 560, "protein_g": 38, "carbs_g": 48, "fat_g": 22},
 "ingredients": [
   {"amount": "1 loaf",    "item": "Cuban or hoagie roll, halved lengthwise","store_section": "Bakery"},
   {"amount": "4 oz",      "item": "pulled pork or deli ham",               "store_section": "Meat/Seafood"},
   {"amount": "4 oz",      "item": "deli ham",                              "store_section": "Meat/Seafood"},
   {"amount": "4 slices",  "item": "Swiss cheese",                          "store_section": "Dairy/Eggs"},
   {"amount": "8",         "item": "dill pickle slices",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "yellow mustard",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",    "item": "butter, softened",                      "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Spread mustard on the inside of both halves of the roll.",
   "Layer ham, pulled pork, Swiss cheese, and pickles on the bottom half.",
   "Close the sandwich and press firmly.",
   "Butter the outside of both sides of the bread.",
   "Cook in a panini press or weighted skillet over medium heat, pressing down firmly.",
   "Cook 3-4 minutes per side until bread is golden and cheese is melted.",
   "Slice diagonally and serve immediately.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free Swiss.",
   "gluten_free": "Use a gluten-free roll.",
 }},

{"name": "Grilled Chicken Sandwich",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 38, "carbs_g": 44, "fat_g": 14},
 "ingredients": [
   {"amount": "2",         "item": "chicken breasts, pounded thin","store_section": "Meat/Seafood"},
   {"amount": "2",         "item": "brioche burger buns",          "store_section": "Bakery"},
   {"amount": "2 slices",  "item": "provolone or Swiss cheese",    "store_section": "Dairy/Eggs"},
   {"amount": "4 leaves",  "item": "romaine lettuce",              "store_section": "Produce"},
   {"amount": "1/2",       "item": "avocado, sliced",              "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "mayonnaise",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "olive oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "garlic powder",                "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",              "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season chicken with garlic powder, salt, and pepper.",
   "Heat olive oil in a grill pan or skillet over medium-high heat.",
   "Cook chicken 5-6 minutes per side until cooked through. Add cheese for last minute.",
   "Toast buns cut-side down in the same pan.",
   "Spread mayo on both halves of each bun.",
   "Build sandwich: bottom bun, lettuce, chicken with cheese, avocado, top bun.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free alternative.",
   "gluten_free": "Use a gluten-free bun.",
   "low_carb": "Serve in lettuce wraps instead of a bun.",
 }},

{"name": "Loaded Baked Potato Soup",
 "meal_type": "Lunch", "servings": 6, "prep_time": "15 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 14, "carbs_g": 48, "fat_g": 20},
 "ingredients": [
   {"amount": "6 large",   "item": "russet potatoes, peeled and cubed","store_section": "Produce"},
   {"amount": "6 strips",  "item": "bacon, diced",                     "store_section": "Meat/Seafood"},
   {"amount": "1 large",   "item": "onion, diced",                     "store_section": "Produce"},
   {"amount": "3 cloves",  "item": "garlic, minced",                   "store_section": "Produce"},
   {"amount": "4 cups",    "item": "chicken broth",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",     "item": "sour cream",                       "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",     "item": "shredded cheddar cheese",          "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "butter",                           "store_section": "Dairy/Eggs"},
   {"amount": "3 tbsp",    "item": "all-purpose flour",                "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",    "item": "milk",                             "store_section": "Dairy/Eggs"},
   {"amount": "to taste",  "item": "salt and pepper",                  "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook bacon in a large pot until crispy. Remove and set aside.",
   "Saute onion in drippings 5 minutes. Add garlic and cook 1 minute.",
   "Add butter and flour, stir 2 minutes. Whisk in broth and milk.",
   "Add potatoes. Simmer 20 minutes until very tender.",
   "Mash some potatoes against the side of the pot for a thick, chunky texture.",
   "Stir in sour cream and half the cheese. Season with salt and pepper.",
   "Top bowls with remaining cheese, bacon, and extra sour cream.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk, dairy-free sour cream, and vegan cheese.",
   "gluten_free": "Replace flour with cornstarch (1.5 tbsp).",
   "vegetarian": "Skip bacon and use vegetable broth.",
 }},

{"name": "Philly Cheesesteak",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 580, "protein_g": 42, "carbs_g": 46, "fat_g": 24},
 "ingredients": [
   {"amount": "3/4 lb",    "item": "ribeye steak, very thinly sliced","store_section": "Meat/Seafood"},
   {"amount": "2",         "item": "hoagie rolls, split",             "store_section": "Bakery"},
   {"amount": "1 large",   "item": "onion, thinly sliced",            "store_section": "Produce"},
   {"amount": "6 slices",  "item": "provolone cheese",                "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "vegetable oil",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "Worcestershire sauce",            "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",                 "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Ask your butcher to slice the ribeye paper-thin, or freeze 30 minutes and slice yourself.",
   "Heat oil in a large cast iron skillet over high heat.",
   "Cook onion, stirring, until caramelized, about 8 minutes. Push to the side.",
   "Add steak in a single layer. Season and cook 1-2 minutes, then chop and stir with onions.",
   "Add Worcestershire sauce. Divide meat into 2 portions in the pan.",
   "Lay 3 slices of provolone over each portion. Cover 1 minute until melted.",
   "Scoop into toasted hoagie rolls.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free provolone.",
   "gluten_free": "Use a gluten-free hoagie roll.",
   "low_carb": "Serve the steak mixture over cauliflower rice or in lettuce cups.",
 },
 "notes": "Very thin slicing is everything. Ask your butcher or partially freeze the meat first."},

{"name": "Shrimp Tacos",
 "meal_type": "Lunch", "servings": 4, "prep_time": "15 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 28, "carbs_g": 38, "fat_g": 12},
 "ingredients": [
   {"amount": "1 lb",      "item": "large shrimp, peeled and deveined","store_section": "Meat/Seafood"},
   {"amount": "8",         "item": "corn tortillas (6-inch)",          "store_section": "Bakery"},
   {"amount": "2 cups",    "item": "coleslaw mix",                     "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "mayonnaise",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "lime juice",                       "store_section": "Produce"},
   {"amount": "2 tsp",     "item": "chili powder",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "cumin",                            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "garlic powder",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "olive oil",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",   "item": "fresh cilantro",                   "store_section": "Produce"},
   {"amount": "1",         "item": "lime, cut into wedges",            "store_section": "Produce"},
 ],
 "instructions": [
   "Toss shrimp with chili powder, cumin, garlic powder, salt, and olive oil.",
   "Mix coleslaw with mayonnaise and lime juice. Season with salt.",
   "Cook shrimp in a hot skillet 1-2 minutes per side until pink and slightly charred.",
   "Warm tortillas in a dry skillet or directly over a flame.",
   "Fill each tortilla with slaw, shrimp, and cilantro.",
   "Serve with lime wedges.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Corn tortillas are naturally gluten-free.",
   "low_carb": "Serve in lettuce cups instead of tortillas.",
 }},

{"name": "Turkey Avocado Wrap",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 460, "protein_g": 32, "carbs_g": 42, "fat_g": 18},
 "ingredients": [
   {"amount": "2 large",   "item": "flour tortillas",               "store_section": "Bakery"},
   {"amount": "6 oz",      "item": "deli turkey, sliced",           "store_section": "Meat/Seafood"},
   {"amount": "1 large",   "item": "avocado, sliced",               "store_section": "Produce"},
   {"amount": "4 slices",  "item": "provolone or Swiss cheese",     "store_section": "Dairy/Eggs"},
   {"amount": "2 cups",    "item": "romaine lettuce, shredded",     "store_section": "Produce"},
   {"amount": "1/4 cup",   "item": "red onion, thinly sliced",      "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "mayonnaise",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "Dijon mustard",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",  "item": "salt and pepper",               "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Mix mayonnaise and Dijon mustard. Spread over each tortilla.",
   "Layer turkey, cheese, avocado, lettuce, and red onion down the center.",
   "Season with salt and pepper.",
   "Fold in the sides and roll tightly. Slice in half diagonally.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free alternative.",
   "gluten_free": "Use a gluten-free wrap.",
   "low_carb": "Wrap everything in large lettuce leaves.",
 }},

{"name": "Wedge Salad",
 "meal_type": "Lunch", "servings": 4, "prep_time": "10 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 12, "carbs_g": 8, "fat_g": 22},
 "ingredients": [
   {"amount": "1 head",    "item": "iceberg lettuce, cut into 4 wedges","store_section": "Produce"},
   {"amount": "8 strips",  "item": "bacon, cooked and crumbled",        "store_section": "Meat/Seafood"},
   {"amount": "1/2 cup",   "item": "blue cheese crumbles",              "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",   "item": "blue cheese dressing",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",   "item": "red onion, finely diced",           "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "fresh chives, chopped",             "store_section": "Produce"},
   {"amount": "to taste",  "item": "black pepper",                      "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook bacon until crispy and crumble. Set aside.",
   "Cut iceberg lettuce through the core into 4 equal wedges. Keep core intact.",
   "Place each wedge on a plate, cut-side up.",
   "Drizzle blue cheese dressing generously over each wedge.",
   "Top with bacon, blue cheese crumbles, red onion, and chives.",
   "Finish with cracked black pepper.",
 ],
 "substitutions": {
   "dairy_free": "Use a dairy-free ranch dressing and skip blue cheese.",
   "gluten_free": "Already gluten-free.",
   "vegetarian": "Skip bacon and add extra cheese and avocado.",
 }},

]

for r in recipes:
    fn = r['name'].lower().replace(' ', '-').replace('&', 'and').replace("'", '').replace(',', '') + '.json'
    (OUT / fn).write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {fn}')
print(f'Done — {len(recipes)} lunch recipes.')
