#!/usr/bin/env python3
"""One-time script to generate all 29 recipe JSON files."""
import json
from pathlib import Path

OUT = Path(__file__).parent / 'data'
OUT.mkdir(exist_ok=True)

recipes = [

# ── BREAKFAST ────────────────────────────────────────────────────────────────

{"name": "Banana Protein Pancakes",
 "meal_type": "Breakfast", "servings": 2, "prep_time": "5 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 28, "carbs_g": 48, "fat_g": 8},
 "ingredients": [
   {"amount": "2 large",   "item": "ripe bananas",          "store_section": "Produce"},
   {"amount": "2",         "item": "eggs",                   "store_section": "Dairy/Eggs"},
   {"amount": "1 scoop",   "item": "vanilla protein powder", "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",   "item": "rolled oats",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",     "item": "baking powder",          "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",   "item": "cinnamon",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",    "item": "coconut oil",             "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Mash bananas in a large bowl until smooth.",
   "Add eggs, protein powder, oats, baking powder, and cinnamon. Mix well.",
   "Heat coconut oil in a non-stick skillet over medium heat.",
   "Pour 1/4 cup batter per pancake. Cook 2-3 minutes until bubbles form.",
   "Flip and cook another 1-2 minutes until golden. Serve warm.",
 ],
 "substitutions": {
   "dairy_free": "Protein powder is already dairy-free if using plant-based variety.",
   "gluten_free": "Use certified gluten-free oats.",
   "low_carb": "Replace oats with 2 tbsp almond flour and reduce banana to 1.",
   "vegan": "Replace eggs with 2 flax eggs (2 tbsp ground flax + 6 tbsp water).",
 },
 "notes": "Freeze extras between parchment paper for easy weekday breakfasts."},

{"name": "Veggie Omelette",
 "meal_type": "Breakfast", "servings": 1, "prep_time": "5 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 280, "protein_g": 22, "carbs_g": 8, "fat_g": 18},
 "ingredients": [
   {"amount": "3 large",   "item": "eggs",                    "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",    "item": "milk",                    "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",   "item": "bell pepper, diced",      "store_section": "Produce"},
   {"amount": "1/4 cup",   "item": "mushrooms, sliced",       "store_section": "Produce"},
   {"amount": "2 tbsp",    "item": "onion, diced",            "store_section": "Produce"},
   {"amount": "1 cup",     "item": "baby spinach",            "store_section": "Produce"},
   {"amount": "1/4 cup",   "item": "shredded cheddar cheese", "store_section": "Dairy/Eggs"},
   {"amount": "1 tbsp",    "item": "butter",                  "store_section": "Dairy/Eggs"},
   {"amount": "to taste",  "item": "salt and pepper",         "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Whisk eggs with milk, salt, and pepper until combined.",
   "Melt butter in a non-stick skillet over medium heat.",
   "Sauté bell pepper, mushrooms, and onion 3-4 minutes until softened.",
   "Add spinach and cook 1 minute until wilted. Push veggies to one side.",
   "Pour egg mixture over entire pan. Let set around the edges, 2 minutes.",
   "Sprinkle cheese over one half. Fold omelette in half over the filling. Serve.",
 ],
 "substitutions": {
   "dairy_free": "Use oat milk instead of milk, dairy-free butter, and vegan cheese.",
   "low_carb": "Already low-carb — skip the milk for even fewer carbs.",
   "vegan": "Use Just Egg or a tofu scramble base instead of eggs.",
 }},

{"name": "Classic French Toast",
 "meal_type": "Breakfast", "servings": 2, "prep_time": "5 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 340, "protein_g": 12, "carbs_g": 52, "fat_g": 9},
 "ingredients": [
   {"amount": "4 thick slices", "item": "brioche or Texas toast", "store_section": "Bakery"},
   {"amount": "2 large",        "item": "eggs",                    "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",        "item": "milk",                    "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",          "item": "vanilla extract",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",          "item": "cinnamon",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",         "item": "butter",                  "store_section": "Dairy/Eggs"},
   {"amount": "2 tbsp",         "item": "maple syrup",             "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Whisk eggs, milk, vanilla, and cinnamon together in a shallow bowl.",
   "Melt butter in a large skillet over medium heat.",
   "Dip each bread slice in the egg mixture, coating both sides well.",
   "Cook 2-3 minutes per side until golden brown.",
   "Serve with maple syrup and fresh fruit if desired.",
 ],
 "substitutions": {
   "dairy_free": "Use almond or oat milk and dairy-free butter.",
   "gluten_free": "Use gluten-free bread.",
   "low_carb": "Use low-carb bread and sugar-free syrup.",
 }},

{"name": "Overnight Oats",
 "meal_type": "Breakfast", "servings": 1, "prep_time": "5 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 15, "carbs_g": 62, "fat_g": 12},
 "ingredients": [
   {"amount": "1/2 cup",  "item": "rolled oats",           "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "milk",                  "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",  "item": "Greek yogurt",          "store_section": "Dairy/Eggs"},
   {"amount": "1 tbsp",   "item": "chia seeds",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",   "item": "honey",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 tsp",  "item": "vanilla extract",       "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",  "item": "mixed berries",         "store_section": "Produce"},
   {"amount": "1 tbsp",   "item": "peanut butter",         "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Combine oats, milk, yogurt, chia seeds, honey, and vanilla in a jar or bowl.",
   "Stir well until fully mixed.",
   "Cover and refrigerate overnight or at least 4 hours.",
   "In the morning, stir and top with berries and peanut butter.",
 ],
 "substitutions": {
   "dairy_free": "Use almond or oat milk and coconut yogurt.",
   "gluten_free": "Use certified gluten-free oats.",
   "vegan": "Replace honey with maple syrup and use plant-based yogurt.",
 },
 "notes": "Keeps in the fridge up to 3 days. Prep a week's worth on Sunday."},

{"name": "Breakfast Burrito",
 "meal_type": "Breakfast", "servings": 2, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 520, "protein_g": 28, "carbs_g": 48, "fat_g": 22},
 "ingredients": [
   {"amount": "4 large",    "item": "eggs",                       "store_section": "Dairy/Eggs"},
   {"amount": "4 strips",   "item": "bacon",                      "store_section": "Meat/Seafood"},
   {"amount": "1/2 cup",    "item": "shredded cheddar cheese",    "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",    "item": "salsa",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",    "item": "flour tortillas",            "store_section": "Bakery"},
   {"amount": "1/2",        "item": "avocado, sliced",            "store_section": "Produce"},
   {"amount": "2 tbsp",     "item": "sour cream",                 "store_section": "Dairy/Eggs"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook bacon in a skillet until crispy. Drain and chop. Reserve 1 tbsp drippings.",
   "Scramble eggs in the same skillet over medium-low heat until just set.",
   "Warm tortillas in a dry pan or microwave for 30 seconds.",
   "Layer eggs, bacon, cheese, salsa, avocado, and sour cream down the center of each tortilla.",
   "Fold in the sides and roll tightly. Slice in half and serve.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cheese and skip sour cream or use coconut-based sour cream.",
   "gluten_free": "Use corn tortillas or gluten-free wraps.",
   "low_carb": "Serve in a low-carb wrap or as a bowl over cauliflower rice.",
   "vegetarian": "Replace bacon with black beans or sautéed peppers.",
 }},

# ── LUNCH ────────────────────────────────────────────────────────────────────

{"name": "Chicken Caesar Wrap",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 38, "carbs_g": 42, "fat_g": 16},
 "ingredients": [
   {"amount": "2",          "item": "chicken breasts",          "store_section": "Meat/Seafood"},
   {"amount": "2 large",    "item": "flour tortillas",          "store_section": "Bakery"},
   {"amount": "2 cups",     "item": "romaine lettuce, chopped", "store_section": "Produce"},
   {"amount": "1/4 cup",    "item": "Caesar dressing",         "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",    "item": "shredded parmesan",       "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",    "item": "croutons",                "store_section": "Bakery"},
   {"amount": "1 tbsp",     "item": "olive oil",               "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt, pepper, garlic powder", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season chicken with salt, pepper, and garlic powder.",
   "Heat olive oil in a skillet over medium-high heat. Cook chicken 6-7 minutes per side until cooked through.",
   "Rest 5 minutes then slice thin.",
   "Toss romaine with Caesar dressing and parmesan.",
   "Lay tortilla flat. Add salad, chicken, and croutons down the center.",
   "Fold sides in and roll tightly. Slice in half diagonally.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free Caesar dressing and skip parmesan.",
   "gluten_free": "Use gluten-free wrap and skip croutons.",
   "low_carb": "Serve as a salad bowl instead of a wrap.",
 }},

{"name": "Spicy Tuna Rice Bowl",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 32, "carbs_g": 48, "fat_g": 10},
 "ingredients": [
   {"amount": "2 pouches",  "item": "tuna in water (2.6 oz each)", "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",      "item": "jasmine rice, dry",           "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "mayonnaise",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "sriracha",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "soy sauce",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1",          "item": "avocado, sliced",             "store_section": "Produce"},
   {"amount": "1/2 cup",    "item": "cucumber, diced",             "store_section": "Produce"},
   {"amount": "2 tbsp",     "item": "green onions, chopped",       "store_section": "Produce"},
   {"amount": "1 tsp",      "item": "sesame seeds",                "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Cook rice according to package directions.",
   "Drain tuna and mix with mayonnaise and sriracha until combined.",
   "Drizzle cooked rice with soy sauce and stir to coat.",
   "Divide rice between 2 bowls. Top with spicy tuna, avocado, and cucumber.",
   "Garnish with green onions and sesame seeds.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use tamari instead of soy sauce.",
   "low_carb": "Replace rice with cauliflower rice.",
 }},

{"name": "Classic Chili",
 "meal_type": "Lunch", "servings": 6, "prep_time": "15 minutes", "cook_time": "45 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 28, "carbs_g": 32, "fat_g": 14},
 "ingredients": [
   {"amount": "1.5 lbs",    "item": "ground beef",             "store_section": "Meat/Seafood"},
   {"amount": "1 large",    "item": "onion, diced",            "store_section": "Produce"},
   {"amount": "3 cloves",   "item": "garlic, minced",          "store_section": "Produce"},
   {"amount": "1 can",      "item": "diced tomatoes (14 oz)",  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 can",      "item": "tomato sauce (15 oz)",    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cans",     "item": "kidney beans, drained",   "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "chili powder",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "cumin",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "paprika",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and pepper",         "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Brown ground beef in a large pot over medium-high heat. Drain fat.",
   "Add onion and garlic. Cook 5 minutes until softened.",
   "Stir in chili powder, cumin, and paprika. Cook 1 minute.",
   "Add diced tomatoes, tomato sauce, and beans. Stir well.",
   "Bring to a boil then reduce heat. Simmer 30 minutes, stirring occasionally.",
   "Taste and season with salt and pepper. Serve with sour cream and shredded cheese.",
 ],
 "substitutions": {
   "dairy_free": "Skip sour cream and cheese toppings or use dairy-free versions.",
   "gluten_free": "Already gluten-free.",
   "low_carb": "Skip the beans and add diced bell peppers instead.",
   "vegetarian": "Replace ground beef with an extra can of beans and 1 cup diced mushrooms.",
 },
 "notes": "Tastes even better the next day. Freezes great for up to 3 months."},

{"name": "Tomato Basil Soup",
 "meal_type": "Lunch", "servings": 4, "prep_time": "10 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 180, "protein_g": 5, "carbs_g": 22, "fat_g": 8},
 "ingredients": [
   {"amount": "2 cans",     "item": "whole peeled tomatoes (28 oz)", "store_section": "Pantry/Dry Goods"},
   {"amount": "1 large",    "item": "onion, chopped",                "store_section": "Produce"},
   {"amount": "4 cloves",   "item": "garlic, minced",               "store_section": "Produce"},
   {"amount": "2 cups",     "item": "chicken broth",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "heavy cream",                   "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",    "item": "fresh basil leaves",            "store_section": "Produce"},
   {"amount": "2 tbsp",     "item": "olive oil",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "sugar",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and pepper",               "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Heat olive oil in a large pot over medium heat. Sauté onion until soft, 5 minutes.",
   "Add garlic and cook 1 minute.",
   "Add tomatoes with juice and chicken broth. Bring to a boil.",
   "Reduce heat and simmer 20 minutes.",
   "Use an immersion blender to blend until smooth.",
   "Stir in heavy cream, basil, and sugar. Season with salt and pepper.",
   "Simmer 5 more minutes. Serve with crusty bread.",
 ],
 "substitutions": {
   "dairy_free": "Replace heavy cream with full-fat coconut milk.",
   "gluten_free": "Already gluten-free — just skip the bread.",
   "vegan": "Use vegetable broth and coconut milk instead of chicken broth and cream.",
   "low_carb": "Skip the sugar and bread, serve as-is.",
 }},

{"name": "BLT Club Sandwich",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "10 minutes",
 "macros_per_serving": {"calories": 520, "protein_g": 28, "carbs_g": 44, "fat_g": 24},
 "ingredients": [
   {"amount": "6 strips",   "item": "bacon",                     "store_section": "Meat/Seafood"},
   {"amount": "6 slices",   "item": "sandwich bread, toasted",   "store_section": "Bakery"},
   {"amount": "4 slices",   "item": "deli turkey",               "store_section": "Meat/Seafood"},
   {"amount": "2 large",    "item": "tomatoes, sliced",          "store_section": "Produce"},
   {"amount": "4 leaves",   "item": "romaine lettuce",           "store_section": "Produce"},
   {"amount": "1/4 cup",    "item": "mayonnaise",                "store_section": "Pantry/Dry Goods"},
   {"amount": "4 slices",   "item": "cheddar cheese",            "store_section": "Dairy/Eggs"},
   {"amount": "1/2",        "item": "avocado, sliced",           "store_section": "Produce"},
 ],
 "instructions": [
   "Cook bacon until crispy. Drain on paper towels.",
   "Toast bread until golden.",
   "Spread mayo on one side of each slice.",
   "Layer: first slice — lettuce, tomato, bacon. Add second slice. Layer turkey, cheese, avocado. Top with third slice.",
   "Secure with toothpicks and cut diagonally into quarters.",
 ],
 "substitutions": {
   "dairy_free": "Skip cheese or use dairy-free slices.",
   "gluten_free": "Use gluten-free bread.",
   "low_carb": "Use lettuce leaves as wraps instead of bread.",
   "vegetarian": "Skip bacon and turkey, add cucumber and extra avocado.",
 }},

{"name": "Greek Chicken Salad",
 "meal_type": "Lunch", "servings": 2, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 35, "carbs_g": 12, "fat_g": 22},
 "ingredients": [
   {"amount": "2",          "item": "chicken breasts",            "store_section": "Meat/Seafood"},
   {"amount": "4 cups",     "item": "romaine lettuce, chopped",   "store_section": "Produce"},
   {"amount": "1 cup",      "item": "cherry tomatoes, halved",    "store_section": "Produce"},
   {"amount": "1",          "item": "cucumber, diced",            "store_section": "Produce"},
   {"amount": "1/2 cup",    "item": "kalamata olives",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "feta cheese, crumbled",      "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",    "item": "red onion, thinly sliced",   "store_section": "Produce"},
   {"amount": "3 tbsp",     "item": "olive oil",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "red wine vinegar",           "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "dried oregano",              "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season chicken with salt, pepper, and oregano.",
   "Cook in a skillet with 1 tbsp olive oil over medium-high heat, 6-7 minutes per side.",
   "Rest 5 minutes then slice.",
   "Whisk together remaining olive oil, red wine vinegar, oregano, salt, and pepper.",
   "Combine lettuce, tomatoes, cucumber, olives, feta, and red onion in a large bowl.",
   "Top with sliced chicken and drizzle with dressing.",
 ],
 "substitutions": {
   "dairy_free": "Skip feta or use a dairy-free alternative.",
   "gluten_free": "Already gluten-free.",
   "vegan": "Replace chicken with chickpeas and skip feta.",
 }},

# ── DINNER ───────────────────────────────────────────────────────────────────

{"name": "Chicken Alfredo",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 680, "protein_g": 42, "carbs_g": 65, "fat_g": 24},
 "ingredients": [
   {"amount": "1 lb",       "item": "fettuccine pasta",           "store_section": "Pantry/Dry Goods"},
   {"amount": "2",          "item": "chicken breasts",            "store_section": "Meat/Seafood"},
   {"amount": "4 tbsp",     "item": "butter",                     "store_section": "Dairy/Eggs"},
   {"amount": "4 cloves",   "item": "garlic, minced",             "store_section": "Produce"},
   {"amount": "2 cups",     "item": "heavy cream",                "store_section": "Dairy/Eggs"},
   {"amount": "1.5 cups",   "item": "grated parmesan",            "store_section": "Dairy/Eggs"},
   {"amount": "1 tbsp",     "item": "olive oil",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt, pepper, Italian seasoning", "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "fresh parsley, chopped",     "store_section": "Produce"},
 ],
 "instructions": [
   "Cook fettuccine according to package directions. Reserve 1 cup pasta water before draining.",
   "Season chicken with salt, pepper, and Italian seasoning.",
   "Cook chicken in olive oil over medium-high heat, 6-7 minutes per side. Rest and slice.",
   "In the same pan, melt butter over medium heat. Add garlic and cook 1 minute.",
   "Pour in heavy cream. Bring to a simmer and cook 5 minutes until slightly thickened.",
   "Stir in parmesan until melted and smooth. Add pasta water if sauce is too thick.",
   "Toss pasta in sauce, top with sliced chicken and fresh parsley.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free butter, coconut cream, and nutritional yeast instead of parmesan.",
   "gluten_free": "Use gluten-free pasta.",
   "low_carb": "Serve over zucchini noodles or spaghetti squash.",
 }},

{"name": "Street Beef Tacos",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 28, "carbs_g": 38, "fat_g": 16},
 "ingredients": [
   {"amount": "1.5 lbs",    "item": "ground beef or skirt steak", "store_section": "Meat/Seafood"},
   {"amount": "8",          "item": "corn tortillas (6-inch)",    "store_section": "Bakery"},
   {"amount": "1",          "item": "white onion, finely diced",  "store_section": "Produce"},
   {"amount": "1/2 cup",    "item": "fresh cilantro, chopped",    "store_section": "Produce"},
   {"amount": "2",          "item": "limes",                      "store_section": "Produce"},
   {"amount": "1/2 cup",    "item": "salsa verde",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1",          "item": "avocado, diced",             "store_section": "Produce"},
   {"amount": "2 tsp",      "item": "cumin",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",      "item": "chili powder",               "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Season beef with cumin, chili powder, salt, and pepper.",
   "Cook over medium-high heat, breaking up meat, until browned and cooked through, about 10 minutes.",
   "Warm tortillas directly on a gas burner or in a dry skillet until lightly charred.",
   "Double up tortillas per taco for sturdiness.",
   "Fill with beef, then top with onion, cilantro, avocado, and salsa verde.",
   "Squeeze fresh lime over each taco before serving.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Corn tortillas are naturally gluten-free.",
   "low_carb": "Serve in lettuce cups instead of tortillas.",
   "vegetarian": "Replace beef with seasoned black beans and roasted sweet potato.",
 }},

{"name": "Teriyaki Salmon",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 38, "carbs_g": 22, "fat_g": 18},
 "ingredients": [
   {"amount": "4 fillets",  "item": "salmon (6 oz each)",         "store_section": "Meat/Seafood"},
   {"amount": "1/4 cup",    "item": "soy sauce",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "honey",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "rice vinegar",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "sesame oil",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "3 cloves",   "item": "garlic, minced",             "store_section": "Produce"},
   {"amount": "1 tsp",      "item": "fresh ginger, grated",       "store_section": "Produce"},
   {"amount": "1 tbsp",     "item": "cornstarch",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "green onions, sliced",       "store_section": "Produce"},
   {"amount": "1 tsp",      "item": "sesame seeds",               "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Whisk soy sauce, honey, rice vinegar, sesame oil, garlic, ginger, and cornstarch together.",
   "Heat an oven-safe skillet over medium-high heat with a little oil.",
   "Sear salmon skin-side up for 3 minutes. Flip and pour sauce over fillets.",
   "Transfer to a 400°F oven and bake 8-10 minutes until cooked through.",
   "Spoon pan sauce over salmon. Garnish with green onions and sesame seeds.",
   "Serve over steamed rice or vegetables.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use tamari or coconut aminos instead of soy sauce.",
   "low_carb": "Serve over cauliflower rice and reduce honey to 1 tsp.",
 }},

{"name": "Slow Cooker Pulled Pork",
 "meal_type": "Dinner", "servings": 8, "prep_time": "15 minutes", "cook_time": "8 hours",
 "macros_per_serving": {"calories": 380, "protein_g": 42, "carbs_g": 8, "fat_g": 18},
 "ingredients": [
   {"amount": "4 lbs",      "item": "pork shoulder (bone-in)",   "store_section": "Meat/Seafood"},
   {"amount": "1 cup",      "item": "BBQ sauce",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "apple cider vinegar",       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "brown sugar",               "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",      "item": "smoked paprika",            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",      "item": "garlic powder",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tsp",      "item": "onion powder",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "cumin",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and black pepper",     "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Mix paprika, garlic powder, onion powder, cumin, salt, and pepper into a dry rub.",
   "Rub all over the pork shoulder generously.",
   "Place pork in slow cooker. Mix BBQ sauce, vinegar, and brown sugar, pour over pork.",
   "Cook on LOW 8 hours or HIGH 5 hours until meat is fall-apart tender.",
   "Remove pork and shred with two forks. Discard excess fat.",
   "Return shredded pork to slow cooker and mix with juices. Serve on buns.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use gluten-free BBQ sauce and serve on gluten-free buns.",
   "low_carb": "Skip the buns and serve over coleslaw.",
 },
 "notes": "Leftovers keep 4 days refrigerated. Excellent for meal prep."},

{"name": "Chicken Stir Fry",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "15 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 35, "carbs_g": 32, "fat_g": 10},
 "ingredients": [
   {"amount": "1.5 lbs",    "item": "chicken breast, sliced thin",  "store_section": "Meat/Seafood"},
   {"amount": "2 cups",     "item": "broccoli florets",              "store_section": "Produce"},
   {"amount": "1",          "item": "red bell pepper, sliced",       "store_section": "Produce"},
   {"amount": "1 cup",      "item": "snap peas",                     "store_section": "Produce"},
   {"amount": "1 cup",      "item": "carrots, julienned",            "store_section": "Produce"},
   {"amount": "3 cloves",   "item": "garlic, minced",                "store_section": "Produce"},
   {"amount": "1 tbsp",     "item": "fresh ginger, grated",          "store_section": "Produce"},
   {"amount": "3 tbsp",     "item": "soy sauce",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "oyster sauce",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "sesame oil",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "vegetable oil",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "cornstarch",                    "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Toss chicken slices with cornstarch, salt, and pepper.",
   "Heat vegetable oil in a wok or large skillet over high heat until smoking.",
   "Cook chicken in batches, 3-4 minutes until golden. Remove and set aside.",
   "Add more oil if needed. Stir fry carrots and broccoli 3 minutes.",
   "Add bell pepper, snap peas, garlic, and ginger. Cook 2 more minutes.",
   "Return chicken. Add soy sauce, oyster sauce, and sesame oil. Toss to coat.",
   "Serve immediately over steamed rice.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use tamari instead of soy sauce and gluten-free oyster sauce.",
   "low_carb": "Serve over cauliflower rice.",
   "vegetarian": "Replace chicken with tofu or tempeh and skip oyster sauce.",
 }},

{"name": "Baked Lemon Herb Chicken",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "30 minutes",
 "macros_per_serving": {"calories": 320, "protein_g": 42, "carbs_g": 4, "fat_g": 14},
 "ingredients": [
   {"amount": "4",          "item": "chicken breasts",            "store_section": "Meat/Seafood"},
   {"amount": "3 tbsp",     "item": "olive oil",                  "store_section": "Pantry/Dry Goods"},
   {"amount": "2",          "item": "lemons, juiced and zested",  "store_section": "Produce"},
   {"amount": "4 cloves",   "item": "garlic, minced",             "store_section": "Produce"},
   {"amount": "1 tsp",      "item": "dried rosemary",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "dried thyme",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "dried oregano",              "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 425°F.",
   "Whisk olive oil, lemon juice, lemon zest, garlic, rosemary, thyme, oregano, salt, and pepper.",
   "Pound chicken breasts to even thickness. Place in a baking dish.",
   "Pour marinade over chicken, turning to coat. Marinate 30 minutes if time allows.",
   "Bake 25-30 minutes until internal temperature reaches 165°F.",
   "Rest 5 minutes before slicing. Spoon pan juices over top.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Already gluten-free.",
   "low_carb": "Already low-carb — pair with roasted vegetables.",
   "vegan": "Use the same marinade on thick cauliflower steaks or portobello mushrooms.",
 },
 "notes": "Great for meal prep — slice and use in salads, wraps, or bowls all week."},

{"name": "Shrimp Fried Rice",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 420, "protein_g": 28, "carbs_g": 52, "fat_g": 10},
 "ingredients": [
   {"amount": "1 lb",       "item": "large shrimp, peeled and deveined", "store_section": "Meat/Seafood"},
   {"amount": "3 cups",     "item": "cooked jasmine rice (day-old)",     "store_section": "Pantry/Dry Goods"},
   {"amount": "3",          "item": "eggs, beaten",                      "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",      "item": "frozen peas and carrots",           "store_section": "Frozen"},
   {"amount": "3 cloves",   "item": "garlic, minced",                    "store_section": "Produce"},
   {"amount": "3 tbsp",     "item": "soy sauce",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "sesame oil",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "vegetable oil",                     "store_section": "Pantry/Dry Goods"},
   {"amount": "3",          "item": "green onions, sliced",              "store_section": "Produce"},
 ],
 "instructions": [
   "Heat oil in a large wok or skillet over high heat.",
   "Cook shrimp 1-2 minutes per side until pink. Remove and set aside.",
   "Add garlic to the pan and cook 30 seconds.",
   "Add frozen peas and carrots, cook 2 minutes.",
   "Push vegetables to the side. Scramble eggs in the empty space until just set.",
   "Add cold rice and break up any clumps. Stir fry everything together 3-4 minutes.",
   "Return shrimp. Add soy sauce and sesame oil. Toss well. Garnish with green onions.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use tamari instead of soy sauce.",
   "low_carb": "Replace rice with cauliflower rice — cook 2 minutes less.",
   "vegetarian": "Replace shrimp with edamame or extra eggs.",
 },
 "notes": "Day-old rice works best — fresh rice gets mushy. Make rice the night before."},

{"name": "BBQ Baby Back Ribs",
 "meal_type": "Dinner", "servings": 4, "prep_time": "15 minutes", "cook_time": "3 hours 30 minutes",
 "macros_per_serving": {"calories": 680, "protein_g": 48, "carbs_g": 22, "fat_g": 42},
 "ingredients": [
   {"amount": "2 racks",    "item": "baby back pork ribs",       "store_section": "Meat/Seafood"},
   {"amount": "1 cup",      "item": "BBQ sauce",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "brown sugar",               "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "smoked paprika",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "garlic powder",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "onion powder",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "cayenne pepper",            "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt and black pepper",     "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 275°F.",
   "Remove membrane from back of ribs by sliding a knife under it and pulling off.",
   "Mix brown sugar, paprika, garlic powder, onion powder, cayenne, salt, and pepper.",
   "Rub dry rub generously over both sides of ribs.",
   "Wrap tightly in foil and bake 3 hours.",
   "Unwrap ribs. Brush generously with BBQ sauce on both sides.",
   "Broil or grill 5-10 minutes until sauce is caramelized. Rest 5 minutes before cutting.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use gluten-free BBQ sauce.",
   "low_carb": "Use sugar-free BBQ sauce and skip the brown sugar.",
 },
 "notes": "Low and slow is the secret. Don't rush the 3-hour oven cook."},

{"name": "Chicken Tikka Masala",
 "meal_type": "Dinner", "servings": 4, "prep_time": "20 minutes", "cook_time": "35 minutes",
 "macros_per_serving": {"calories": 480, "protein_g": 38, "carbs_g": 28, "fat_g": 22},
 "ingredients": [
   {"amount": "2 lbs",      "item": "chicken breast, cubed",      "store_section": "Meat/Seafood"},
   {"amount": "1 cup",      "item": "plain yogurt",               "store_section": "Dairy/Eggs"},
   {"amount": "1 can",      "item": "crushed tomatoes (28 oz)",   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",      "item": "heavy cream",                "store_section": "Dairy/Eggs"},
   {"amount": "1 large",    "item": "onion, diced",               "store_section": "Produce"},
   {"amount": "4 cloves",   "item": "garlic, minced",             "store_section": "Produce"},
   {"amount": "1 tbsp",     "item": "fresh ginger, grated",       "store_section": "Produce"},
   {"amount": "2 tbsp",     "item": "garam masala",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "cumin",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "paprika",                    "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "butter",                     "store_section": "Dairy/Eggs"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Marinate chicken in yogurt, half the garam masala, and salt for at least 30 minutes.",
   "Broil marinated chicken 8-10 minutes until slightly charred. Set aside.",
   "Melt butter in a large pan. Sauté onion until golden, 8 minutes.",
   "Add garlic and ginger. Cook 2 minutes.",
   "Add remaining spices and cook 1 minute.",
   "Pour in crushed tomatoes. Simmer 15 minutes.",
   "Stir in cream and broiled chicken. Simmer 10 more minutes.",
   "Serve over basmati rice with naan bread.",
 ],
 "substitutions": {
   "dairy_free": "Use coconut yogurt for the marinade and coconut cream instead of heavy cream.",
   "gluten_free": "Already gluten-free — serve with rice instead of naan.",
   "low_carb": "Skip the rice and naan, serve with cauliflower rice.",
 }},

{"name": "Spaghetti Bolognese",
 "meal_type": "Dinner", "servings": 6, "prep_time": "15 minutes", "cook_time": "1 hour",
 "macros_per_serving": {"calories": 520, "protein_g": 32, "carbs_g": 58, "fat_g": 18},
 "ingredients": [
   {"amount": "1 lb",       "item": "spaghetti",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1 lb",       "item": "ground beef",                 "store_section": "Meat/Seafood"},
   {"amount": "1/2 lb",     "item": "ground pork",                 "store_section": "Meat/Seafood"},
   {"amount": "1 large",    "item": "onion, finely diced",         "store_section": "Produce"},
   {"amount": "2",          "item": "carrots, finely diced",       "store_section": "Produce"},
   {"amount": "2 stalks",   "item": "celery, finely diced",        "store_section": "Produce"},
   {"amount": "4 cloves",   "item": "garlic, minced",              "store_section": "Produce"},
   {"amount": "1 can",      "item": "crushed tomatoes (28 oz)",    "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "whole milk",                  "store_section": "Dairy/Eggs"},
   {"amount": "1/4 cup",    "item": "dry red wine",                "store_section": "Beverages"},
   {"amount": "2 tbsp",     "item": "olive oil",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "grated parmesan",             "store_section": "Dairy/Eggs"},
 ],
 "instructions": [
   "Heat olive oil in a large heavy pot. Sauté onion, carrots, and celery 8 minutes.",
   "Add garlic and cook 1 minute.",
   "Add ground beef and pork. Cook until browned, breaking up the meat.",
   "Pour in wine and cook until evaporated, 3 minutes.",
   "Add crushed tomatoes and milk. Stir well.",
   "Reduce heat to low and simmer uncovered 45 minutes, stirring occasionally.",
   "Season with salt and pepper. Serve over spaghetti topped with parmesan.",
 ],
 "substitutions": {
   "dairy_free": "Skip milk and parmesan, use a splash of beef broth instead.",
   "gluten_free": "Use gluten-free pasta.",
   "low_carb": "Serve sauce over zucchini noodles or spaghetti squash.",
   "vegetarian": "Use lentils and mushrooms instead of meat.",
 },
 "notes": "The milk is traditional and makes the sauce creamy — don't skip it."},

{"name": "Honey Garlic Pork Chops",
 "meal_type": "Dinner", "servings": 4, "prep_time": "10 minutes", "cook_time": "20 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 35, "carbs_g": 18, "fat_g": 16},
 "ingredients": [
   {"amount": "4",          "item": "bone-in pork chops (1-inch thick)", "store_section": "Meat/Seafood"},
   {"amount": "3 tbsp",     "item": "honey",                             "store_section": "Pantry/Dry Goods"},
   {"amount": "4 cloves",   "item": "garlic, minced",                    "store_section": "Produce"},
   {"amount": "2 tbsp",     "item": "soy sauce",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "apple cider vinegar",               "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "olive oil",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tbsp",     "item": "butter",                            "store_section": "Dairy/Eggs"},
   {"amount": "to taste",   "item": "salt and pepper",                   "store_section": "Pantry/Dry Goods"},
   {"amount": "fresh",      "item": "parsley for garnish",               "store_section": "Produce"},
 ],
 "instructions": [
   "Pat pork chops dry and season both sides with salt and pepper.",
   "Mix honey, garlic, soy sauce, and apple cider vinegar in a small bowl.",
   "Heat olive oil in an oven-safe skillet over medium-high heat.",
   "Sear pork chops 3-4 minutes per side until golden brown.",
   "Reduce heat to medium. Add butter and honey garlic sauce. Spoon sauce over chops.",
   "Cook 3-5 more minutes until internal temperature reaches 145°F.",
   "Rest 3 minutes. Spoon sauce over top and garnish with parsley.",
 ],
 "substitutions": {
   "dairy_free": "Replace butter with olive oil or dairy-free butter.",
   "gluten_free": "Use tamari instead of soy sauce.",
   "low_carb": "Reduce honey to 1 tbsp or use a sugar-free alternative.",
 }},

# ── SNACKS ───────────────────────────────────────────────────────────────────

{"name": "Protein Energy Balls",
 "meal_type": "Snacks", "servings": 12, "prep_time": "15 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 180, "protein_g": 8, "carbs_g": 22, "fat_g": 8},
 "ingredients": [
   {"amount": "1 cup",      "item": "rolled oats",                "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "peanut butter",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1/3 cup",    "item": "honey",                      "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "chocolate chips",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 scoop",    "item": "protein powder",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "chia seeds",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "vanilla extract",            "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Combine all ingredients in a large bowl. Mix until fully combined.",
   "Refrigerate the mixture for 30 minutes to firm up.",
   "Roll into 12 equal balls using your hands.",
   "Store in an airtight container in the refrigerator.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free chocolate chips.",
   "gluten_free": "Use certified gluten-free oats.",
   "vegan": "Replace honey with maple syrup and use plant-based protein powder.",
   "low_carb": "Replace oats with almond flour and honey with 2 tbsp allulose.",
 },
 "notes": "Keeps refrigerated up to 1 week. Freeze for up to 3 months."},

{"name": "Guacamole and Chips",
 "meal_type": "Snacks", "servings": 6, "prep_time": "10 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 220, "protein_g": 3, "carbs_g": 28, "fat_g": 12},
 "ingredients": [
   {"amount": "3 ripe",     "item": "avocados",                   "store_section": "Produce"},
   {"amount": "2",          "item": "limes, juiced",              "store_section": "Produce"},
   {"amount": "1/2",        "item": "red onion, finely diced",    "store_section": "Produce"},
   {"amount": "2",          "item": "roma tomatoes, diced",       "store_section": "Produce"},
   {"amount": "1",          "item": "jalapeño, minced",           "store_section": "Produce"},
   {"amount": "1/4 cup",    "item": "fresh cilantro, chopped",    "store_section": "Produce"},
   {"amount": "2 cloves",   "item": "garlic, minced",             "store_section": "Produce"},
   {"amount": "to taste",   "item": "salt and pepper",            "store_section": "Pantry/Dry Goods"},
   {"amount": "1 bag",      "item": "tortilla chips",             "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Halve and pit the avocados. Scoop flesh into a bowl.",
   "Mash with a fork to your preferred texture (chunky or smooth).",
   "Stir in lime juice, red onion, tomatoes, jalapeño, cilantro, and garlic.",
   "Season generously with salt and pepper.",
   "Serve immediately with tortilla chips.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Use certified gluten-free tortilla chips.",
   "low_carb": "Serve with cucumber slices or bell pepper strips instead of chips.",
   "vegan": "Already vegan.",
 },
 "notes": "Press plastic wrap directly onto the surface of leftover guac to prevent browning."},

{"name": "Hummus with Veggies",
 "meal_type": "Snacks", "servings": 6, "prep_time": "10 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 160, "protein_g": 6, "carbs_g": 18, "fat_g": 7},
 "ingredients": [
   {"amount": "2 cans",     "item": "chickpeas, drained (15 oz each)", "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 cup",    "item": "tahini",                          "store_section": "Pantry/Dry Goods"},
   {"amount": "3 tbsp",     "item": "olive oil",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "2",          "item": "lemons, juiced",                  "store_section": "Produce"},
   {"amount": "2 cloves",   "item": "garlic",                          "store_section": "Produce"},
   {"amount": "1/2 tsp",    "item": "cumin",                           "store_section": "Pantry/Dry Goods"},
   {"amount": "to taste",   "item": "salt",                            "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "ice water",                       "store_section": "Other"},
   {"amount": "assorted",   "item": "carrots, cucumber, celery, bell pepper", "store_section": "Produce"},
 ],
 "instructions": [
   "Blend chickpeas, tahini, lemon juice, garlic, and cumin in a food processor 1 minute.",
   "With the processor running, drizzle in olive oil and ice water.",
   "Blend 2-3 more minutes until very smooth and creamy.",
   "Season with salt. Transfer to a bowl and drizzle with olive oil.",
   "Serve with sliced raw vegetables.",
 ],
 "substitutions": {
   "dairy_free": "Already dairy-free.",
   "gluten_free": "Already gluten-free.",
   "vegan": "Already vegan.",
   "low_carb": "Increase veggie dippers, reduce chickpea portion.",
 },
 "notes": "Ice water is the secret to ultra-creamy hummus. Don't skip it."},

{"name": "Spinach Artichoke Dip",
 "meal_type": "Snacks", "servings": 8, "prep_time": "10 minutes", "cook_time": "25 minutes",
 "macros_per_serving": {"calories": 240, "protein_g": 8, "carbs_g": 12, "fat_g": 18},
 "ingredients": [
   {"amount": "10 oz",      "item": "frozen spinach, thawed and squeezed dry", "store_section": "Frozen"},
   {"amount": "14 oz",      "item": "artichoke hearts, drained and chopped",   "store_section": "Pantry/Dry Goods"},
   {"amount": "8 oz",       "item": "cream cheese, softened",                  "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",    "item": "sour cream",                              "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",    "item": "mayonnaise",                              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",      "item": "shredded mozzarella",                     "store_section": "Dairy/Eggs"},
   {"amount": "1/2 cup",    "item": "grated parmesan",                         "store_section": "Dairy/Eggs"},
   {"amount": "3 cloves",   "item": "garlic, minced",                          "store_section": "Produce"},
   {"amount": "to taste",   "item": "salt and pepper",                         "store_section": "Pantry/Dry Goods"},
   {"amount": "tortilla chips or bread", "item": "for serving",                "store_section": "Bakery"},
 ],
 "instructions": [
   "Preheat oven to 375°F.",
   "Mix cream cheese, sour cream, and mayonnaise until smooth.",
   "Stir in spinach, artichokes, garlic, half the mozzarella, and parmesan.",
   "Season with salt and pepper.",
   "Transfer to a baking dish. Top with remaining mozzarella.",
   "Bake 20-25 minutes until bubbly and golden on top.",
   "Serve hot with tortilla chips, pita, or crusty bread.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cream cheese, sour cream, and vegan mozzarella.",
   "gluten_free": "Serve with gluten-free chips or veggies — the dip itself is gluten-free.",
   "low_carb": "Serve with celery, cucumber, or bell pepper strips.",
 }},

# ── DESSERTS ─────────────────────────────────────────────────────────────────

{"name": "Chocolate Chip Cookies",
 "meal_type": "Desserts", "servings": 24, "prep_time": "15 minutes", "cook_time": "12 minutes",
 "macros_per_serving": {"calories": 180, "protein_g": 2, "carbs_g": 26, "fat_g": 8},
 "ingredients": [
   {"amount": "2.25 cups",  "item": "all-purpose flour",           "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "baking soda",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "salt",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1 cup",      "item": "butter, softened",            "store_section": "Dairy/Eggs"},
   {"amount": "3/4 cup",    "item": "granulated sugar",            "store_section": "Pantry/Dry Goods"},
   {"amount": "3/4 cup",    "item": "brown sugar, packed",         "store_section": "Pantry/Dry Goods"},
   {"amount": "2 large",    "item": "eggs",                        "store_section": "Dairy/Eggs"},
   {"amount": "2 tsp",      "item": "vanilla extract",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 cups",     "item": "chocolate chips",             "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 375°F. Line baking sheets with parchment paper.",
   "Whisk flour, baking soda, and salt together in a bowl.",
   "Beat butter and both sugars until light and fluffy, 3-4 minutes.",
   "Beat in eggs one at a time, then vanilla.",
   "Gradually mix in flour mixture until just combined.",
   "Fold in chocolate chips.",
   "Drop rounded tablespoons onto prepared baking sheets, 2 inches apart.",
   "Bake 9-11 minutes until edges are golden but centers look slightly underdone.",
   "Cool on baking sheet 5 minutes before transferring to a wire rack.",
 ],
 "substitutions": {
   "dairy_free": "Use vegan butter and dairy-free chocolate chips.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use vegan butter and replace each egg with 1 flax egg.",
 },
 "notes": "Pull them out when they look slightly underbaked — they firm up as they cool."},

{"name": "Banana Bread",
 "meal_type": "Desserts", "servings": 10, "prep_time": "10 minutes", "cook_time": "60 minutes",
 "macros_per_serving": {"calories": 240, "protein_g": 4, "carbs_g": 42, "fat_g": 7},
 "ingredients": [
   {"amount": "3 large",    "item": "very ripe bananas",           "store_section": "Produce"},
   {"amount": "1/3 cup",    "item": "butter, melted",              "store_section": "Dairy/Eggs"},
   {"amount": "3/4 cup",    "item": "sugar",                       "store_section": "Pantry/Dry Goods"},
   {"amount": "1 large",    "item": "egg, beaten",                 "store_section": "Dairy/Eggs"},
   {"amount": "1 tsp",      "item": "vanilla extract",             "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "baking soda",                 "store_section": "Pantry/Dry Goods"},
   {"amount": "1/4 tsp",    "item": "salt",                        "store_section": "Pantry/Dry Goods"},
   {"amount": "1.5 cups",   "item": "all-purpose flour",           "store_section": "Pantry/Dry Goods"},
   {"amount": "1/2 cup",    "item": "chocolate chips (optional)",  "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Preheat oven to 350°F. Butter a 4x8 inch loaf pan.",
   "Mash bananas thoroughly in a large bowl.",
   "Mix in melted butter.",
   "Stir in sugar, beaten egg, and vanilla.",
   "Add baking soda and salt. Mix well.",
   "Fold in flour until just combined. Do not overmix.",
   "Fold in chocolate chips if using.",
   "Pour into loaf pan. Bake 55-65 minutes until a toothpick comes out clean.",
   "Cool in pan 10 minutes then transfer to a wire rack.",
 ],
 "substitutions": {
   "dairy_free": "Use melted coconut oil instead of butter.",
   "gluten_free": "Use a 1:1 gluten-free flour blend.",
   "vegan": "Use coconut oil and a flax egg (1 tbsp ground flax + 3 tbsp water).",
   "low_carb": "Use almond flour, reduce sugar to 2 tbsp and add 1/4 cup allulose.",
 },
 "notes": "The blacker the banana, the sweeter and more flavorful the bread."},

{"name": "No-Bake Cheesecake",
 "meal_type": "Desserts", "servings": 8, "prep_time": "20 minutes", "cook_time": "0 minutes",
 "macros_per_serving": {"calories": 380, "protein_g": 6, "carbs_g": 38, "fat_g": 22},
 "ingredients": [
   {"amount": "2 cups",     "item": "graham cracker crumbs",       "store_section": "Pantry/Dry Goods"},
   {"amount": "6 tbsp",     "item": "butter, melted",              "store_section": "Dairy/Eggs"},
   {"amount": "16 oz",      "item": "cream cheese, softened",      "store_section": "Dairy/Eggs"},
   {"amount": "1 cup",      "item": "powdered sugar",              "store_section": "Pantry/Dry Goods"},
   {"amount": "1 tsp",      "item": "vanilla extract",             "store_section": "Pantry/Dry Goods"},
   {"amount": "2 tbsp",     "item": "lemon juice",                 "store_section": "Produce"},
   {"amount": "1.5 cups",   "item": "heavy whipping cream",        "store_section": "Dairy/Eggs"},
   {"amount": "1 can",      "item": "cherry or strawberry pie filling", "store_section": "Pantry/Dry Goods"},
 ],
 "instructions": [
   "Mix graham cracker crumbs and melted butter. Press firmly into the bottom of a 9-inch springform pan.",
   "Refrigerate crust 15 minutes.",
   "Beat cream cheese until smooth. Add powdered sugar, vanilla, and lemon juice. Beat until fluffy.",
   "In a separate bowl, whip heavy cream to stiff peaks.",
   "Gently fold whipped cream into cream cheese mixture.",
   "Pour filling over crust and smooth the top.",
   "Refrigerate at least 4 hours or overnight.",
   "Top with pie filling before serving.",
 ],
 "substitutions": {
   "dairy_free": "Use dairy-free cream cheese and coconut whipped cream.",
   "gluten_free": "Use gluten-free graham crackers for the crust.",
   "low_carb": "Use almond flour crust (1.5 cups almond flour + 4 tbsp melted butter), sugar-free powdered sweetener, and fresh berries instead of pie filling.",
 },
 "notes": "Overnight refrigeration gives the best set. Do not freeze — texture becomes grainy."},

]  # end of recipes list

saved = 0
for r in recipes:
    filename = r['name'].lower().replace(' ', '-').replace('&', 'and').replace("'", '') + '.json'
    path = OUT / filename
    path.write_text(json.dumps(r, indent=2), encoding='utf-8')
    print(f'  Saved: {filename}')
    saved += 1

print(f'\nDone — {saved} recipes saved to data/')
